@extends('layouts/layoutMaster')
@section('title', $case->case_number)
@section('content')
<div class="container-xxl flex-grow-1 container-p-y"><h4>{{ $case->case_number }}</h4><p class="text-muted">{{ $case->player->full_name }} · {{ $case->event->name }}</p>@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif @php($disciplinaryEnabled = \App\Models\SiteSetting::disciplinarySystemEnabled()) @unless($disciplinaryEnabled)<div class="alert alert-warning">The disciplinary case system is currently disabled. This record remains available to read, but responses and appeals are paused.</div>@endunless
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Notice</h5></div><div class="card-body"><p><strong>Status:</strong> {{ str($case->status)->replace('_',' ')->title() }}</p><p style="white-space:pre-wrap">{{ $case->summary }}</p>@foreach($case->charges as $charge)<div class="border rounded p-3"><strong>{{ $charge->rule_title }}</strong><p class="mb-0">{{ $charge->allegation }}</p></div>@endforeach</div></div>
@if($disciplinaryEnabled && $case->status === 'awaiting_response')<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Submit response</h5></div><div class="card-body"><p>Your response is due {{ $case->response_due_at?->format('d M Y H:i') }}.</p><form method="POST" action="{{ route('disciplinary.my-cases.respond',$case) }}">@csrf<textarea name="response" class="form-control mb-3" rows="8" required minlength="10"></textarea><button class="btn btn-primary">Submit response</button></form></div></div>@endif
@foreach($case->decisions as $decision)<div class="card border-success mb-4"><div class="card-header"><h5 class="mb-0">Panel decision</h5></div><div class="card-body"><p><strong>{{ str($decision->outcome)->replace('_',' ')->title() }}</strong></p><p style="white-space:pre-wrap">{{ $decision->reasons }}</p>@foreach($decision->sanctions as $sanction)<div class="alert alert-warning">{{ str($sanction->type)->replace('_',' ')->title() }} · {{ ucfirst($sanction->scope) }} @if($sanction->ends_at)until {{ $sanction->ends_at->format('d M Y') }}@endif</div>@endforeach</div></div>@endforeach
@if($disciplinaryEnabled && $case->status === 'decided' && !$case->appeals->whereIn('status',['submitted','under_review'])->count())<div class="card"><div class="card-header"><h5 class="mb-0">Appeal</h5></div><div class="card-body"><form method="POST" action="{{ route('disciplinary.my-cases.appeal',$case) }}">@csrf<textarea name="grounds" class="form-control mb-3" rows="6" required minlength="20" placeholder="State the grounds for appeal"></textarea><button class="btn btn-outline-primary">Submit appeal</button></form></div></div>@endif
</div>
@endsection
