<?php
  $event = $invitation->batch?->event;
  $logo = $event?->logo ? asset('storage/'.$event->logo) : asset('assets/img/logos/cape-tennis-logo-transparent.png');
  $eventUrl = $event ? route('events.show', $event) : url('/');
  $responseUrl = route('masters.invitations.show', $invitation);
  $eventDate = $event?->start_date?->format('d M Y');
?>
<div style="margin:0;background:#f4f3f8;padding:28px 12px;font-family:Arial,Helvetica,sans-serif;color:#4f4b5f;line-height:1.55;">
  <div style="max-width:620px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #e6e3ed;">
    <div style="background:#7651e8;padding:24px 28px;text-align:center;"><img src="<?php echo e($logo); ?>" alt="Cape Tennis" width="150" style="display:inline-block;max-width:150px;height:auto;border:0;background:#fff;border-radius:8px;padding:7px;"><div style="color:#fff;font-size:12px;letter-spacing:1.5px;text-transform:uppercase;margin-top:12px;">Masters invitation</div></div>
    <div style="padding:30px 32px;"><p style="font-size:22px;font-weight:700;margin:0 0 12px;color:#403b52;">Hello <?php echo e($invitation->player?->full_name ?? 'Player'); ?>,</p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($kind === 'invitation' && filled($messagePayload['body'] ?? null)): ?><p style="font-size:16px;margin:0 0 22px;white-space:pre-line"><?php echo e($messagePayload['body']); ?></p><?php else: ?><p style="font-size:16px;margin:0 0 22px;">You are invited to take part in <strong><?php echo e($event?->name ?? 'the Cape Tennis Masters event'); ?></strong>.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <div style="background:#f7f5ff;border-left:4px solid #7651e8;border-radius:6px;padding:16px 18px;margin:0 0 24px;"><div style="font-size:18px;font-weight:700;color:#403b52;"><?php echo e($invitation->categoryEvent?->category?->name ?? 'Masters category'); ?></div><div style="font-size:14px;color:#6f6a7c;margin-top:4px;">Ranking position: <strong><?php echo e($invitation->ranking_position); ?></strong></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($eventDate): ?><div style="font-size:14px;color:#6f6a7c;">Event date: <strong><?php echo e($eventDate); ?></strong></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event?->venue_name): ?><div style="font-size:14px;color:#6f6a7c;">Venue: <strong><?php echo e($event->venue_name); ?></strong></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($kind === 'invitation' || $kind === 'replacement'): ?><p style="margin:0 0 22px;">Register and complete PayFast payment to play. If you are unavailable, please let us know so the next reserve player can be considered.</p><div style="text-align:center;margin:0 0 26px;"><a href="<?php echo e($eventUrl); ?>" style="display:inline-block;background:#fff;color:#625f6d;text-decoration:none;font-weight:700;border:1px solid #cbc6d8;border-radius:6px;padding:12px 18px;margin:0 4px 8px;">View event</a><a href="<?php echo e($responseUrl); ?>" style="display:inline-block;background:#7651e8;color:#fff;text-decoration:none;font-weight:700;border:1px solid #7651e8;border-radius:6px;padding:12px 18px;margin:0 4px 8px;">Register and pay</a><a href="<?php echo e($responseUrl); ?>" style="display:inline-block;background:#fff;color:#b54747;text-decoration:none;font-weight:700;border:1px solid #d9a6a6;border-radius:6px;padding:12px 18px;margin:0 4px 8px;">I am unavailable</a></div><p style="font-size:13px;color:#777180;margin:-10px 0 0;text-align:center;">These links open the event registration page for the selected player.</p><?php elseif($kind === 'confirmed'): ?><p style="margin:0;">Your PayFast payment has been verified and your place is confirmed. We look forward to seeing you on court.</p><?php elseif($kind === 'declined'): ?><p style="margin:0;">Your unavailability has been recorded. The next reserve player will be contacted after the cancellation is confirmed.</p><p style="text-align:center;margin:24px 0 0;"><a href="<?php echo e(URL::temporarySignedRoute('masters.invitations.confirm-decline', now()->addDays(2), ['invitation' => $invitation])); ?>" style="display:inline-block;background:#625f6d;color:#fff;text-decoration:none;font-weight:700;border-radius:6px;padding:12px 22px;">Confirm unavailability</a></p><?php elseif($kind === 'withdrawn'): ?><p style="margin:0;">Your withdrawal has been recorded. If automatic replacement is enabled, the next reserve player will be contacted.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </div><div style="border-top:1px solid #eeeaf4;padding:18px 32px;text-align:center;color:#8b8794;font-size:12px;">Cape Tennis · Masters administration<br><a href="<?php echo e(url('/')); ?>" style="color:#7651e8;text-decoration:none;">capetennis.co.za</a></div>
  </div>
</div>
<?php /**PATH C:\wamp64\www\ct\resources\views\emails\masters\invitation.blade.php ENDPATH**/ ?>