
<?php $__env->startSection('title', $event->name.' — PayFast refund recovery'); ?>
<?php $__env->startSection('content'); ?>
<div class="container-xl py-4"><h1>PayFast refund recovery</h1><a href="<?php echo e(route('backend.interprovincial-trials.programme.index',$event)); ?>">Regional programme</a>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<p>These attempts already contacted PayFast. Recovery completes local records and never submits another provider refund. Verify provider history before reconciling an uncertain outcome.</p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $attempts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $attempt): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<?php ($participation=\App\Models\TrialParticipation::where('order_id',$attempt->order_id)->first()); ?>
<div class="card mb-3"><div class="card-body"><h2 class="h5"><?php echo e($attempt->order?->player?->full_name); ?> — <?php echo e($attempt->status); ?></h2><p>Order <?php echo e($attempt->order_id); ?> · Original PayFast payment <?php echo e($attempt->pf_payment_id); ?> · Exact refund R <?php echo e(number_format($attempt->amount,2)); ?> · Local status <?php echo e($attempt->order?->refund_status); ?></p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($participation && $attempt->order?->refund_status==='pending'): ?>
<form method="post" action="<?php echo e(route('backend.interprovincial-trials.refund-recovery.recover',[$event,$participation])); ?>"><?php echo csrf_field(); ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($attempt->status==='confirmed'): ?><input type="hidden" name="mode" value="retry"><button class="btn btn-primary">Retry confirmed refund locally</button>
<?php else: ?><input type="hidden" name="mode" value="reconcile"><label>Original PayFast payment ID<input class="form-control" name="pf_payment_id" required maxlength="120"></label><label>Exact externally refunded amount<input class="form-control" name="amount" type="number" step="0.01" min="0.01" required></label><label>Provider refund reference<input class="form-control" name="reference" required minlength="3" maxlength="120"></label><label>Provider confirmation time<input class="form-control" name="confirmed_at" type="datetime-local" required></label><label>Evidence and reason<textarea class="form-control" name="reason" required minlength="10" maxlength="1000"></textarea></label><label class="d-block"><input type="checkbox" name="externally_confirmed" value="1" required> I verified that PayFast completed this exact refund.</label><button class="btn btn-warning mt-2">Record provider evidence and complete locally</button><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</form><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php echo e($attempts->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\interprovincial-trials\refund-recovery.blade.php ENDPATH**/ ?>