<?php
    $reportPrefix = $report['prefix'];
    $reportFilters = $report['filters'];
    $reportContext = $reportContext ?? [];
    $reportUrl = $reportUrl ?? url()->current();
    $reportEvent = $reportEvent ?? null;
    $quickOutcomes = ['all' => 'All', 'sent_complete' => 'Sent', 'failed' => 'Failed', 'pending' => 'Pending', 'skipped' => 'Excluded'];
    $reportLink = function ($outcome) use ($reportPrefix, $reportContext, $reportUrl, $report) {
        $query = array_merge(request()->except([$report['page'], $reportPrefix.'outcome']), $reportContext);
        if ($outcome !== 'all') $query[$reportPrefix.'outcome'] = $outcome;
        return $reportUrl.'?'.http_build_query($query).'#email-history';
    };
?>
<style>
.mail-report{font-size:1rem}.mail-report .mail-quick{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.6rem}.mail-report .mail-quick a{color:#263d5b;background:#fff;border:1px solid #d6dde7;border-radius:.5rem;padding:.85rem;text-decoration:none;min-width:0}.mail-report .mail-quick a[aria-current=page]{border-color:#235b96;box-shadow:0 0 0 1px #235b96}.mail-report .mail-quick strong{display:block;font-size:1.45rem}.mail-report .mail-report-row{display:grid;grid-template-columns:minmax(150px,1fr) minmax(180px,1.5fr) minmax(160px,1fr) 110px 140px;gap:1rem;align-items:center;padding:1rem;border-top:1px solid #d6dde7;background:#fff}.mail-report .mail-report-row>div{min-width:0;overflow-wrap:anywhere}.mail-report .mail-report-list{border:1px solid #d6dde7;border-radius:.5rem;overflow:hidden}.mail-report .mail-report-head{background:#f2f5f8;font-weight:600;font-size:.875rem}.mail-report .mail-report-secondary{font-size:.875rem;color:#526174}.ct-backend .mail-report .mail-report-action .btn:not(.p-0):not(.btn-icon){min-height:44px;min-width:68px;white-space:nowrap}.mail-report a{color:#174d83}.mail-report .btn-outline-secondary{color:#42536a;border-color:#8392a5}.mail-report .mail-report-neutral{background:#edf1f5;color:#42536a}.mail-report .badge{white-space:normal;font-size:.875rem;line-height:1.4}.mail-report .mail-quick a:hover{border-color:#235b96}.mail-report .pagination{flex-wrap:wrap}@media(max-width:991.98px){.mail-report .mail-report-row{grid-template-columns:minmax(0,1fr) minmax(0,1.3fr)}.mail-report .mail-report-head{display:none}}@media(max-width:575.98px){.mail-report .mail-quick{grid-template-columns:repeat(2,minmax(0,1fr))}.mail-report .mail-report-row{grid-template-columns:minmax(0,1fr);gap:.65rem}.mail-report .mail-report-action{display:flex;gap:.5rem}.mail-report .mail-report-row .mail-report-date{font-size:.875rem}.mail-report .mail-report-row>div{width:100%}}
</style>
<section class="mail-report mb-4" id="email-history" aria-label="Email history">
<div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-3"><h2 class="h4 mb-0"><?php echo e($reportTitle ?? 'Email history'); ?></h2><span class="mail-report-secondary"><?php echo e(number_format($report['logs']->total())); ?> matching records</span></div>
<div class="mail-quick mb-3">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $quickOutcomes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<a href="<?php echo e($reportLink($value)); ?>" <?php if(($reportFilters['outcome'] ?? 'all')===$value): ?> aria-current="page" <?php endif; ?>><span><?php echo e($label); ?></span><strong><?php echo e(number_format($report['counts'][$value])); ?></strong></a>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div>
<p class="mail-report-secondary">Counts reflect current filters for search, dates, type and report scope, before outcome filtering. <?php echo e(number_format($report['recipientCount'])); ?> recipient records; <?php echo e(number_format($report['copyCount'])); ?> copies.</p>
<p class="mail-report-secondary">Sent includes completed historical sends without acceptance evidence. It excludes sandbox and uncertain outcomes. Inbox delivery is not confirmed. <a href="<?php echo e($reportLink('accepted')); ?>"><?php echo e(number_format($report['counts']['accepted'])); ?> server accepted</a> &middot; <a href="<?php echo e($reportLink('uncertain')); ?>"><?php echo e(number_format($report['counts']['uncertain'])); ?> acceptance uncertain</a>.</p>
<form method="get" action="<?php echo e($reportUrl); ?>" class="card card-body mb-3">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $reportContext; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><input type="hidden" name="<?php echo e($key); ?>" value="<?php echo e($value); ?>"><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<div class="row g-3"><div class="col-md-6"><label class="form-label" for="<?php echo e($reportPrefix); ?>search">Search recipient or subject</label><input class="form-control" id="<?php echo e($reportPrefix); ?>search" name="<?php echo e($reportPrefix); ?>search" value="<?php echo e($reportFilters['search'] ?? ''); ?>" maxlength="200"></div><div class="col-md-6"><label class="form-label" for="<?php echo e($reportPrefix); ?>outcome">Outcome</label><select class="form-select" id="<?php echo e($reportPrefix); ?>outcome" name="<?php echo e($reportPrefix); ?>outcome"><option value="">All outcomes</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = \App\Services\MailReportFilters::OUTCOMES; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(($reportFilters['outcome'] ?? '')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div></div>
<details class="mt-3" <?php if(!empty($reportFilters['mail_type']) || !empty($reportFilters['from']) || !empty($reportFilters['until'])): ?> open <?php endif; ?>><summary>Type and date filters</summary><div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label" for="<?php echo e($reportPrefix); ?>mail_type">Email type</label><select class="form-select" id="<?php echo e($reportPrefix); ?>mail_type" name="<?php echo e($reportPrefix === 'mail_' ? 'mail_type' : $reportPrefix.'mail_type'); ?>"><option value="">All recorded types</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $report['types']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(($reportFilters['mail_type'] ?? '')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div><div class="col-md-3"><label class="form-label" for="<?php echo e($reportPrefix); ?>from">From</label><input class="form-control" type="date" id="<?php echo e($reportPrefix); ?>from" name="<?php echo e($reportPrefix); ?>from" value="<?php echo e(old($reportPrefix.'from',$reportFilters['from'] ?? '')); ?>"></div><div class="col-md-3"><label class="form-label" for="<?php echo e($reportPrefix); ?>until">Until</label><input class="form-control" type="date" id="<?php echo e($reportPrefix); ?>until" name="<?php echo e($reportPrefix); ?>until" value="<?php echo e(old($reportPrefix.'until',$reportFilters['until'] ?? '')); ?>"></div></div></details>
<div class="d-flex flex-wrap gap-2 mt-3"><button class="btn btn-primary">Apply filters</button><a class="btn btn-outline-secondary" href="<?php echo e($reportUrl.'?'.http_build_query($reportContext).'#email-history'); ?>">Reset filters</a></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger mt-3 mb-0" role="alert"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</form>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(isset($report['groups'])): ?>
<p class="mail-report-secondary"><?php echo e(number_format($report['groups']->total())); ?> mail sends. Open a send to view its matching recipients and individual outcomes. Historical groups without a batch reference combine the same subject, type, sender and recorded day.</p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $report['groups']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $send): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<details class="card mb-2 mail-send-group" data-mail-send>
<summary class="p-3" style="cursor:pointer;min-height:44px"><strong><?php echo e($send->send_subject); ?></strong><div class="mail-report-secondary mt-1"><?php echo e(\App\Services\SuperAdminMailHistory::typeLabel($send->send_type)); ?> &middot; <?php echo e(\Carbon\Carbon::parse($send->first_recorded)->format('d M Y H:i')); ?> SAST &middot; <?php echo e(number_format($send->recipient_count)); ?> matching records <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(str_starts_with($send->send_key,'legacy:')): ?> &middot; Historical day group <?php else: ?> &middot; <?php echo e(str_starts_with($send->send_key,'batch:') ? 'Batch' : 'Reviewed preview'); ?> #<?php echo e(substr($send->send_key,strpos($send->send_key,':')+1)); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><div class="d-flex flex-wrap gap-2 mt-2"><span>Completed: <?php echo e($send->sent_count); ?></span><span>Failed: <?php echo e($send->failed_count); ?></span><span>Pending: <?php echo e($send->pending_count); ?></span><span>Excluded: <?php echo e($send->skipped_count); ?></span><span>Acceptance uncertain: <?php echo e($send->uncertain_count); ?></span></div></summary>
<div class="p-3 pt-0" data-send-content data-send-url="<?php echo e($reportUrl.'?'.http_build_query(array_merge(request()->except(['history_sends_page','send_recipients_page']),$reportContext,['history_send'=>$send->representative_id]))); ?>"><a class="btn btn-outline-primary" href="<?php echo e($reportUrl.'?'.http_build_query(array_merge(request()->except(['history_sends_page','send_recipients_page']),$reportContext,['history_send'=>$send->representative_id]))); ?>">Open recipient list</a></div>
</details>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="card p-4 text-center">No logged emails match these filters.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($report['groups']->hasPages()): ?><div class="mt-3"><?php echo e($report['groups']->links('pagination::bootstrap-5')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<script>
(function () {
    const section = document.getElementById('email-history');
    if (!section) return;
    async function load(content, url) {
        if (content.dataset.loading) return;
        content.dataset.loading = '1';
        content.setAttribute('aria-busy', 'true');
        const status = document.createElement('p');
        status.setAttribute('role', 'status'); status.textContent = 'Loading recipients...'; content.prepend(status);
        try {
            const response = await fetch(url, {credentials: 'same-origin', headers: {'X-Requested-With': 'XMLHttpRequest'}});
            if (!response.ok || response.redirected) throw new Error('Unable to load recipients.');
            content.innerHTML = await response.text(); content.dataset.loaded = '1';
        } catch (error) {
            status.textContent = 'Could not load recipients. Use the link below to try again.';
            if (!content.querySelector('a')) { const retry = document.createElement('a'); retry.href = url; retry.textContent = 'Try again'; content.append(retry); }
        } finally { delete content.dataset.loading; content.removeAttribute('aria-busy'); }
    }
    section.querySelectorAll('[data-mail-send]').forEach(group => {
        group.addEventListener('toggle', () => { const content = group.querySelector('[data-send-content]'); if (group.open && !content.dataset.loaded) load(content, content.dataset.sendUrl); });
    });
    section.addEventListener('click', event => {
        const link = event.target.closest('[data-send-content] a');
        if (!link || event.ctrlKey || event.metaKey || event.shiftKey || event.altKey) return;
        if (link.closest('[data-send-pagination]') || !link.closest('[data-send-content]').dataset.loaded) {event.preventDefault(); load(link.closest('[data-send-content]'), link.href);}
    });
})();
</script>
<?php else: ?>
<div class="mail-report-list"><div class="mail-report-row mail-report-head"><div>Recipient</div><div>Subject / type</div><div>Outcome</div><div>Recorded</div><div>Action</div></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $report['logs']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $mail): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<?php
    $reportSubject = $mail->history_subject ?? ($reportEvent ? \App\Services\EventMailLogService::subject($mail) : 'Subject not recorded');
    [$tone,$label] = match(true) {
        $mail->status==='sent' && $mail->evidence_status==='server_accepted' && $mail->accepted_at => ['success','Server accepted'],
        $mail->status==='sent' && $mail->evidence_status==='sandbox_accepted' && $mail->accepted_at => ['secondary','Sandbox accepted'],
        $mail->status==='sent' => ['secondary','Sent - evidence unverified'],
        $mail->status==='acceptance_unknown' => ['warning','Acceptance uncertain'],
        $mail->status==='failed' => ['danger','Failed'],
        $mail->status==='skipped' => ['secondary','Excluded'],
        default => ['primary',$mail->delivery_status_label],
    };
?>
<article class="mail-report-row"><div><strong><?php echo e($mail->recipient_name ?: $mail->recipient_email); ?></strong><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($mail->recipient_name): ?><div class="mail-report-secondary"><?php echo e($mail->recipient_email); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><div><strong><?php echo e($reportSubject); ?></strong><div class="mail-report-secondary"><?php echo e(\App\Services\SuperAdminMailHistory::typeLabel($mail->mail_type)); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(in_array(data_get($mail->payload,'recipient_kind'),['admin_copy','sender_copy'])): ?> &middot; Copy <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><div><span class="badge bg-label-<?php echo e($tone); ?> <?php if($tone==='secondary'): ?> mail-report-neutral <?php endif; ?>"><?php echo e($label); ?></span><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($mail->status==='failed'): ?><div class="mail-report-secondary mt-1"><?php echo e(\App\Services\EventMailLogService::explanation($mail) ?: 'Review this failed attempt before retrying.'); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><div class="mail-report-date"><?php echo e($mail->created_at?->format('d M Y')); ?><div class="mail-report-secondary"><?php echo e($mail->created_at?->format('H:i')); ?> SAST</div></div><div class="mail-report-action"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($reportEvent): ?><a class="btn btn-outline-primary" href="<?php echo e(route('backend.event-mail-log.show',[$reportEvent,$mail])); ?>">Open</a>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($mail->status==='failed' && !$mail->sent_at && !$mail->accepted_at): ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(in_array($mail->mail_type,['team_selection_invitation','interprovincial_trial_invitation']) || (data_get($mail->payload,'event_communication_batch_id') && \App\Models\EventCommunicationBatch::whereKey(data_get($mail->payload,'event_communication_batch_id'))->where('event_id',$reportEvent->id)->where('created_by',auth()->id())->exists())): ?>
<form method="post" action="<?php echo e(route('backend.event-communications.retry-preview',[$reportEvent,$mail])); ?>" data-mail-launch><?php echo csrf_field(); ?><button class="btn btn-outline-primary mt-2">Review retry</button></form>
<?php elseif($reportEvent->isInterprovincialTrials() && data_get($mail->payload,'preview_id')): ?>
<details class="mt-2"><summary>Review retry</summary><strong><?php echo e(data_get($mail->payload,'subject')); ?></strong><pre style="white-space:pre-wrap;overflow-wrap:anywhere"><?php echo e(html_entity_decode(strip_tags(data_get($mail->payload,'body','')), ENT_QUOTES | ENT_HTML5, 'UTF-8')); ?></pre><form method="post" action="<?php echo e(route('backend.interprovincial-trials.communications.retry',[$reportEvent,$mail])); ?>"><?php echo csrf_field(); ?><label><input type="checkbox" name="approved_retry" value="1" required> I reviewed and approve this exact recipient and message.</label><button class="btn btn-outline-primary mt-2">Approve retry</button></form></details>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php else: ?><span class="mail-report-secondary">Metadata only</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></article>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="p-4 text-center"><strong>No logged emails match these filters.</strong><p class="mail-report-secondary mb-0 mt-2">Try a different outcome or reset the filters.</p></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($report['logs']->hasPages()): ?><div class="mt-3"><?php echo e($report['logs']->links('pagination::bootstrap-5')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</section>
<?php /**PATH C:\wamp64\www\ct\resources\views\backend\partials\mail-report.blade.php ENDPATH**/ ?>