<?php
  $event = $invitation->selectionImport?->event;
  $campaign = $campaign ?? [];
  $responseUrl = route('team-selection.invitations.show', $invitation);
  $eventLogo = basename((string) $event?->logo);
  $eventLogoPath = $eventLogo !== '' ? 'assets/img/logos/'.$eventLogo : null;
  $logo = $eventLogoPath && is_file(public_path($eventLogoPath))
    ? asset($eventLogoPath)
    : asset('assets/img/logos/cape-tennis-logo-transparent.png');
  $message = $campaign['message'] ?? $invitation->selectionImport?->email_message;
  $includeClothing = (bool) ($campaign['include_clothing'] ?? $invitation->selectionImport?->include_clothing);
  $eventDetails = $campaign['event'] ?? [];
  $clothingItems = collect($campaign['clothing_items'] ?? []);
  $publicEventUrl = $eventDetails['public_url'] ?? ($event?->published ? route('events.show', $event) : null);
  $registrationUrl = route('events.show', [
    'event' => $invitation->event_id,
    'team' => $invitation->team_id,
    'player' => $invitation->player_id,
  ]).'#team-registration-'.$invitation->team_id.'-'.$invitation->player_id;
  $eventName = $eventDetails['name'] ?? $event?->name;
  $isCustomEmail = str_starts_with(($kind ?? 'invitation'), 'custom_');
  $responseDeadline = $isCustomEmail ? null : (($kind ?? 'invitation') === 'invitation' && !empty($campaign['response_deadline']) ? \Illuminate\Support\Carbon::parse($campaign['response_deadline']) : $invitation->effectiveResponseDeadline());
  $shortReplacementWindow = ($kind ?? 'invitation') === 'replacement'
    && $invitation->invited_at
    && $responseDeadline
    && $responseDeadline->lt($invitation->invited_at->copy()->addHours(24));
  $isRegistrationUpdate = ($kind ?? 'invitation') === 'custom_payment_update';
  $isStatusUpdate = ($kind ?? 'invitation') === 'custom_status_update';
  $isPaidUpdate = ($kind ?? 'invitation') === 'custom_paid_update';
?>
<div style="width:100%;margin:0;background:#f4f3f8;padding:28px 12px;box-sizing:border-box;font-family:Arial,Helvetica,sans-serif;color:#4f4b5f;line-height:1.55;word-wrap:break-word">
  <div style="width:100%;max-width:640px;margin:0 auto;background:#fff;border:1px solid #e6e3ed;border-radius:12px;overflow:hidden;box-sizing:border-box">
    <div style="background:#15324b;padding:24px;text-align:center"><img src="<?php echo e($logo); ?>" alt="Cape Tennis" width="150" style="background:#fff;border-radius:8px;padding:7px"><div style="color:#fff;text-transform:uppercase;letter-spacing:1.5px;margin-top:12px"><?php echo e($isPaidUpdate ? 'Confirmed team place update' : ($isStatusUpdate ? 'Team player update' : ($isRegistrationUpdate ? 'Team registration update' : (($kind ?? 'invitation') === 'replacement' ? 'Replacement team invitation' : 'Platteland team invitation')))); ?></div></div>
    <div style="padding:30px 32px;box-sizing:border-box;overflow-wrap:anywhere;word-break:break-word">
      <h2 style="color:#263b50">Hello <?php echo e($invitation->player?->full_name ?? 'Player'); ?>,</h2>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($message): ?><p><?php echo nl2br(e($message)); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <p>You have been selected to represent <strong><?php echo e($invitation->region?->region_name); ?></strong> at <strong><?php echo e($eventName); ?></strong>.</p>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$isPaidUpdate && !$isRegistrationUpdate && $responseDeadline): ?><div style="background:#f5f3ff;border:1px solid #ddd6fe;border-radius:8px;padding:14px 18px;margin:18px 0"><strong><?php echo e(($kind ?? 'invitation') === 'replacement' ? 'Your replacement deadline' : 'Your response deadline'); ?></strong><div style="margin-top:7px">Respond by: <strong><?php echo e($responseDeadline->format('d M Y H:i')); ?></strong></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(($kind ?? 'invitation') === 'replacement'): ?><div style="font-size:12px;color:#6b6475;margin-top:6px">This replacement deadline is the later of the campaign deadline or 24 hours from this invitation, unless the event starts sooner.</div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($shortReplacementWindow): ?><div style="font-weight:bold;color:#b54747;margin-top:7px">The event starts in less than 24 hours. Please respond as soon as possible.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$isPaidUpdate && !$isStatusUpdate): ?><div style="border:1px solid #d9e5eb;border-radius:8px;padding:16px 18px;margin:22px 0"><strong>How to register</strong><ol style="margin:10px 0 0;padding-left:20px"><li>Sign in to a Cape Tennis account.</li><li>Open the event registration page using the green button below.</li><li>Choose <strong>Register</strong> next to the selected player and complete the registration.</li><li>Your team place is secured once Cape Tennis confirms the registration.</li></ol><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$isRegistrationUpdate): ?><p style="margin:10px 0 0">If you are unavailable, let us know promptly so the next reserve can be invited.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <div style="text-align:center;margin:26px 0 10px"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($publicEventUrl): ?><a href="<?php echo e($publicEventUrl); ?>" style="display:inline-block;background:#fff;color:#425466;text-decoration:none;font-weight:bold;border:1px solid #b8c5cf;border-radius:6px;padding:11px 18px;margin:0 4px 8px">View event</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><?php if($isPaidUpdate): ?><a href="<?php echo e($responseUrl); ?>" style="display:inline-block;background:#16876f;color:#fff;text-decoration:none;font-weight:bold;border:1px solid #16876f;border-radius:6px;padding:11px 18px;margin:0 4px 8px">View invitation</a><?php elseif(!$isStatusUpdate): ?><a href="<?php echo e($registrationUrl); ?>" style="display:inline-block;background:#16876f;color:#fff;text-decoration:none;font-weight:bold;border:1px solid #16876f;border-radius:6px;padding:11px 18px;margin:0 4px 8px">Register</a><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$isRegistrationUpdate): ?><a href="<?php echo e($responseUrl); ?>?action=decline" style="display:inline-block;background:#fff;color:#b54747;text-decoration:none;font-weight:bold;border:1px solid #d9a6a6;border-radius:6px;padding:11px 18px;margin:0 4px 8px">Decline invitation</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><?php endif; ?></div>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$isRegistrationUpdate && !$isPaidUpdate && !$isStatusUpdate): ?><p style="font-size:13px;color:#777180;text-align:center">Register opens the event page. Decline opens a confirmation window with an optional reason.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($includeClothing && !$isStatusUpdate): ?><div style="background:#eef7ff;border-radius:8px;padding:16px 18px;margin-top:20px;overflow-wrap:anywhere;word-break:break-word"><strong>Optional regional clothing</strong><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($clothingItems->isNotEmpty()): ?><table role="presentation" width="100%" style="width:100%;table-layout:fixed;border-collapse:collapse;margin-top:9px"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $clothingItems; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td width="72%" style="width:72%;padding:6px 8px 6px 0;border-top:1px solid #d8e8f2;vertical-align:top;overflow-wrap:anywhere;word-break:break-word"><strong><?php echo e($item['name']); ?></strong><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!empty($item['sizes'])): ?><br><span style="font-size:12px;color:#65717a">Sizes: <?php echo e(implode(', ', $item['sizes'])); ?></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></td><td width="28%" style="width:28%;padding:6px 0;border-top:1px solid #d8e8f2;text-align:right;vertical-align:top;white-space:nowrap"><strong>R<?php echo e(number_format((float) $item['price'], 2)); ?></strong></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></table><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><p style="margin:12px 0 0"><strong>How to order:</strong> first complete the event registration and payment. Once payment is verified, go to the main page and click <strong>Order clothing</strong> to order your clothing.</p></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </div>
  </div>
</div>
<?php /**PATH C:\wamp64\www\ct\resources\views\emails\team-selection\invitation.blade.php ENDPATH**/ ?>