<?php $__env->startSection('title', 'Masters invitation'); ?>
<?php $__env->startSection('content'); ?>
<div class="container-xxl flex-grow-1 container-p-y"><a href="<?php echo e(url('/events/'.$invitation->batch->event_id)); ?>" class="btn btn-sm btn-outline-secondary mb-3">Back to event</a><div class="card"><div class="card-body"><h4><?php echo e($invitation->batch->event->name); ?></h4><p class="text-muted"><?php echo e($invitation->categoryEvent->category->name ?? 'Masters category'); ?> · Ranking position <?php echo e($invitation->ranking_position); ?></p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($invitation->status === \App\Models\MastersInvitation::INVITED && ($invitation->batch->registration_open || (int) $invitation->batch->event->signUp === 1)): ?>
<p>Welcome, <?php echo e($invitation->player?->full_name); ?>. Register and complete payment to play.</p><form method="POST" action="<?php echo e(route('masters.invitations.accept', $invitation)); ?>" class="d-inline"><?php echo csrf_field(); ?><button class="btn btn-primary">Register and pay with PayFast</button></form><form method="POST" action="<?php echo e(route('masters.invitations.decline', $invitation)); ?>" class="d-inline ms-2" onsubmit="return confirm('Confirm that you are unavailable for this event?');"><?php echo csrf_field(); ?><button class="btn btn-outline-secondary">I am unavailable</button></form>
<?php elseif($invitation->status === \App\Models\MastersInvitation::INVITED): ?>
<div class="alert alert-info mb-0">The player list is published, but Masters registration is currently closed.</div>
<?php elseif($invitation->status === \App\Models\MastersInvitation::ACCEPTED_PENDING_PAYMENT): ?>
<p>This registration was started but not completed. Cancel it to return to the beginning and restart the registration process.</p><a class="btn btn-warning" href="<?php echo e(route('registration.hybrid.cancel', ['orderId' => $invitation->order_id])); ?>" onclick="return confirm('Cancel this unfinished registration and restart the registration process?');">Restart registration</a>
<?php elseif($invitation->status === \App\Models\MastersInvitation::PAID_CONFIRMED): ?><span class="badge bg-label-success">Payment confirmed — you are entered</span>
<?php elseif($invitation->status === \App\Models\MastersInvitation::DECLINED): ?><div class="alert alert-warning mb-0"><strong>Unavailability recorded.</strong><br>Confirm the cancellation using the link sent to your email. The next player will only be invited after email confirmation.</div>
<?php else: ?><span class="badge bg-label-secondary">This invitation is no longer active.</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts/contentNavbarLayout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\frontend\masters\show.blade.php ENDPATH**/ ?>