
<?php $__env->startSection('title', 'Trials communications'); ?>
<?php $__env->startSection('content'); ?>
<?php echo $__env->make('backend.event.partials.header',['eventWorkspaceActive'=>'communications'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<a class="btn btn-outline-primary mb-3" href="<?php echo e(route('backend.event-mail-log.index',$event)); ?>">Event email log</a>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = ['success'=>'success','warning'=>'warning','error'=>'danger','info'=>'info']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $flash=>$tone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session($flash)): ?><div class="alert alert-<?php echo e($tone); ?>" role="status"><?php echo e(session($flash)); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<a class="btn btn-outline-primary mb-3" href="#email-history">Email history</a>
<div class="mb-4">
<form method="get" class="mb-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = request()->except('person_search'); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(is_scalar($value)): ?><input type="hidden" name="<?php echo e($key); ?>" value="<?php echo e($value); ?>"><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><label>Find an individual <input name="person_search" value="<?php echo e(request('person_search')); ?>" class="form-control" maxlength="100"></label><button class="btn btn-outline-primary">Search players</button><p class="text-muted">Selectors show up to 500 matches. Search by name to find another individual.</p></form>
<h4><?php echo e($event->name); ?> — Invitations and reminders</h4>
<p>Choose recipients, edit the whole message, then review exact combined emails before sending. Invitations are optional.</p>

<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<form method="post" action="<?php echo e(route('backend.interprovincial-trials.communications.preview',$event)); ?>" data-mail-compose class="card card-body mb-4">
<?php echo csrf_field(); ?>
<?php echo $__env->make('backend.partials.email-sender-fields', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($editing): ?><input type="hidden" name="schedule_id" value="<?php echo e($editing->id); ?>"><div class="alert alert-info">Editing reminder schedule <?php echo e($editing->id); ?>. Review and approve its new schedule before changes apply.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<label class="form-label">Saved template</label><select id="trial-template" class="form-select mb-3"><option value="">Write a message</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $templates; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $template): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($template->id); ?>"><?php echo e($template->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select>
<div class="row g-3"><div class="col-md-6"><label class="form-label">Audience</label><select name="audience" class="form-select"><option value="all" <?php if(old('audience',$editing?->options['audience'] ?? 'all')==='all'): echo 'selected'; endif; ?>>Everyone — nominees and current teams</option><option value="nominations" <?php if(old('audience',$editing?->options['audience'] ?? 'all')==='nominations'): echo 'selected'; endif; ?>>All nominated players</option><option value="teams" <?php if(old('audience',$editing?->options['audience'] ?? 'all')==='teams'): echo 'selected'; endif; ?>>Current teams (including draft)</option></select></div>
<div class="col-md-6"><label class="form-label">Region</label><select name="region_id" class="form-select"><option value="">Whole authorised event</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $regions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $region): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($region->id); ?>" <?php if((string)old('region_id',$editing?->options['region_id'] ?? '')===(string)$region->id): echo 'selected'; endif; ?>><?php echo e($region->region_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select><div class="form-text">Trials nominees belong to their programme’s event region.</div></div>
<div class="col-md-6"><label class="form-label">Current status</label><select name="filter" class="form-select"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = ['all'=>'Everyone','not_registered'=>'Not registered / awaiting response','payment_pending'=>'Payment outstanding','paid'=>'Paid','declined'=>'Declined','confirmed'=>'Confirmed']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(($editing?->options['filter'] ?? 'all')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
<div class="col-md-6"><label class="form-label">Categories (leave empty for all)</label><select multiple name="category_ids[]" class="form-select"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category->id); ?>" <?php if(in_array($category->id,$editing?->options['category_ids'] ?? [])): echo 'selected'; endif; ?>><?php echo e($category->category?->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
<div class="col-md-6"><label class="form-label">Teams (leave empty for all)</label><select multiple name="tiers[]" class="form-select"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = ['A','B','C','D','E','F']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $tier): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(in_array($tier,$editing?->options['tiers'] ?? [])): echo 'selected'; endif; ?>><?php echo e($tier); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
<div class="col-md-6"><label class="form-label">Individual nominees (leave empty for all)</label><select multiple name="nominee_ids[]" class="form-select"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $nominees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $nominee): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($nominee->id); ?>" <?php if(($editing?->options['audience'] ?? '')==='nominations' && in_array($nominee->id,$editing?->options['individual_ids'] ?? [])): echo 'selected'; endif; ?>><?php echo e($nominee->player?->full_name ?? trim($nominee->nominee_name.' '.$nominee->nominee_surname)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
<div class="col-md-6"><label class="form-label">Individual team players (leave empty for all)</label><select multiple name="slot_ids[]" class="form-select"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $slots; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $slot): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($slot->id); ?>" <?php if(($editing?->options['audience'] ?? '')==='teams' && in_array($slot->id,$editing?->options['individual_ids'] ?? [])): echo 'selected'; endif; ?>><?php echo e($slot->player?->full_name); ?> — <?php echo e($slot->tier); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div></div>
<label class="form-label mt-3">Recipients</label><select name="recipients" class="form-select"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = ['players'=>'Players and linked parents','managers'=>'Regional managers — selected roster summary','both'=>'Players/parents and regional managers']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(($editing?->options['recipients'] ?? 'players')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select><p class="text-muted">Available at every event stage. Regional managers receive the selected roster for their event region.</p><label class="form-label mt-3">Subject</label><input name="subject" id="trial-subject" class="form-control" required maxlength="255" value="<?php echo e(old('subject',$editing?->subject ?? session('compose_subject','Invitation: {event}'))); ?>">
<label class="form-label mt-3">Message</label><textarea name="body" id="trial-body" rows="10" class="form-control" required><?php echo e(old('body',$editing?->body ?? session('compose_body', "You are invited to {event}.\n\n{players}\n\nFee: R{fee}\nDeadline: {deadline}\n\nRegister or respond on the event page: {url}"))); ?></textarea>
<p class="text-muted mt-2">Available variables: {event}, {players}, {fee}, {deadline}, {url}. All text is editable.</p>
<label class="form-label">Template name (optional)</label><input name="name" class="form-control mb-3" maxlength="255">
<div class="d-flex flex-wrap gap-2"><button class="btn btn-primary">Preview recipients and messages</button><button type="submit" formaction="<?php echo e(route('backend.interprovincial-trials.communications.templates',$event)); ?>" class="btn btn-outline-primary">Save reusable template</button></div>
</form>
</div>
<h5>Send history</h5>
<p><a href="<?php echo e(route('backend.event-communications.index', $event)); ?>">Invitation send report and reviewed failed-email retries</a></p>
<form method="get" class="mb-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = request()->except(['batch','history_page']); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(is_scalar($value)): ?><input type="hidden" name="<?php echo e($key); ?>" value="<?php echo e($value); ?>"><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><label class="form-label">Approved batch</label><select name="batch" class="form-select" onchange="this.form.submit()"><option value="">All event email history</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $batches; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $candidate): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($candidate->id); ?>" <?php if($batch?->id===$candidate->id): echo 'selected'; endif; ?>>#<?php echo e($candidate->id); ?> — <?php echo e($candidate->subject); ?> — <?php echo e(count($candidate->recipients)); ?> approved recipients</option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></form>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($batch): ?><p><?php echo e(count($batch->recipients)); ?> approved recipients; <?php echo e(count($batch->excluded)); ?> contacts requiring follow-up.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php echo $__env->make('backend.partials.mail-report',['report'=>$historyReport,'reportEvent'=>$event,'reportTitle'=>$batch ? 'Selected Trials batch email history' : 'All event email history'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<h5>System messages awaiting review</h5>
<p>Registration, withdrawal and refund messages wait here for exact recipient and message approval.</p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $pendingDrafts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $draft): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="card card-body mb-2"><strong><?php echo e($draft->subject); ?></strong><div><?php echo e(count($draft->recipients)); ?> recipients awaiting review</div><form method="post" action="<?php echo e(route('backend.event-communications.drafts.preview',[$event,$draft])); ?>"><?php echo csrf_field(); ?><button class="btn btn-outline-primary mt-2">Preview exact recipients and messages</button></form></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p>No system messages awaiting review.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($transactionBatches->isNotEmpty()): ?><h5>Approved system-message reports</h5><ul><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $transactionBatches; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $systemBatch): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><a href="<?php echo e(route('backend.event-communications.index',['event'=>$event,'batch'=>$systemBatch->id])); ?>">#<?php echo e($systemBatch->id); ?> — <?php echo e($systemBatch->subject); ?> — mail-server acceptance report</a></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></ul><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<h5>Reminder review schedules</h5><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $schedules; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $schedule): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="card card-body mb-2"><a href="<?php echo e(route('backend.interprovincial-trials.communications.index',$event)); ?>?edit_schedule=<?php echo e($schedule->id); ?>" class="mb-2">Review this reminder / edit schedule</a><div><?php echo e($schedule->subject); ?> — <?php echo e(!$schedule->active ? 'Paused / completed' : ($schedule->next_send_at->isPast() ? 'Due — review and approval required' : 'Awaiting review time')); ?> — next <?php echo e($schedule->next_send_at); ?></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($schedule->active): ?><form method="post" action="<?php echo e(route('backend.interprovincial-trials.communications.pause',[$event,$schedule])); ?>"><?php echo csrf_field(); ?><button class="btn btn-sm btn-outline-warning mt-2">Pause schedule</button></form><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p>No scheduled reminders.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<script>
const templates = <?php echo json_encode($templates->keyBy('id'), 15, 512) ?>;
document.getElementById('trial-template').addEventListener('change',function(){const selected=templates[this.value];if(selected){document.getElementById('trial-subject').value=selected.subject;document.getElementById('trial-body').value=selected.body;}});
</script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\interprovincial-trials\communications.blade.php ENDPATH**/ ?>