<?php $__env->startSection('title', 'Report Disciplinary Incident'); ?>
<?php $__env->startSection('content'); ?>
<div class="container-xxl flex-grow-1 container-p-y">
  <div class="mb-4"><h4 class="mb-1"><i class="ti ti-alert-triangle me-2"></i>Report incident</h4><p class="text-muted mb-0"><?php echo e($event->name); ?> · this creates an allegation for triage, not an automatic finding.</p></div>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><ul class="mb-0"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></ul></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <form method="POST" action="<?php echo e(route('backend.events.disciplinary.store', $event)); ?>" class="card"><?php echo csrf_field(); ?>
    <div class="card-body"><div class="row g-4">
      <div class="col-md-6"><label class="form-label">Player *</label><select name="player_id" class="form-select" required><option value="">Select an entered player</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $players; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $player): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($player->id); ?>" <?php if(old('player_id') == $player->id): echo 'selected'; endif; ?>><?php echo e($player->full_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
      <div class="col-md-6"><label class="form-label">Offence type</label><select name="violation_type_id" class="form-select"><option value="">Other rule</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $violationTypes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($type->id); ?>" <?php if(old('violation_type_id') == $type->id): echo 'selected'; endif; ?>><?php echo e($type->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
      <div class="col-md-4"><label class="form-label">Category</label><select name="category_event_id" class="form-select"><option value="">Not specified</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category->pivot->id); ?>"><?php echo e($category->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
      <div class="col-md-8"><label class="form-label">Fixture</label><select name="fixture_id" class="form-select"><option value="">Not match-specific</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $fixtures; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $fixture): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($fixture->id); ?>">#<?php echo e($fixture->id); ?> · <?php echo e($fixture->registration1?->displayName()); ?> vs <?php echo e($fixture->registration2?->displayName()); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select><small class="text-muted">When selected, the server verifies that the player is in this match.</small></div>
      <div class="col-md-4"><label class="form-label">Incident date and time *</label><input type="datetime-local" name="incident_at" value="<?php echo e(old('incident_at', now()->format('Y-m-d\TH:i'))); ?>" class="form-control" required></div>
      <div class="col-md-4"><label class="form-label">Severity *</label><select name="severity" class="form-select" required><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = ['standard','serious','urgent']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $severity): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($severity); ?>"><?php echo e(ucfirst($severity)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
      <div class="col-md-4"><label class="form-label">Court / location</label><input name="incident_location" value="<?php echo e(old('incident_location')); ?>" class="form-control" maxlength="255"></div>
      <div class="col-md-4"><label class="form-label">Rule code</label><input name="rule_code" value="<?php echo e(old('rule_code')); ?>" class="form-control"></div>
      <div class="col-md-8"><label class="form-label">Other rule title</label><input name="rule_title" value="<?php echo e(old('rule_title')); ?>" class="form-control"><small class="text-muted">Required only if no configured offence type is selected.</small></div>
      <div class="col-12"><label class="form-label">Factual incident summary *</label><textarea name="summary" rows="5" class="form-control" required><?php echo e(old('summary')); ?></textarea></div>
      <div class="col-12"><label class="form-label">Official statement / witness detail</label><textarea name="statement" rows="5" class="form-control"><?php echo e(old('statement')); ?></textarea></div>
    </div></div>
    <div class="card-footer d-flex justify-content-between"><a href="<?php echo e(route('backend.events.disciplinary.index', $event)); ?>" class="btn btn-outline-secondary">Cancel</a><button class="btn btn-primary">Submit for triage</button></div>
  </form>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\disciplinary\cases\create.blade.php ENDPATH**/ ?>