
<?php $__env->startSection('title', 'Schedule audit – '.$event->name); ?>
<?php $__env->startSection('content'); ?>
<div class="container-xxl py-3">
  <div class="d-flex flex-wrap justify-content-between gap-3 mb-3"><div><h3>Schedule audit</h3><p class="text-muted mb-0"><?php echo e($event->name); ?> · <?php echo e($scope['date'] === 'all' ? 'All saved days' : \Carbon\Carbon::parse($scope['date'])->format('D j M Y')); ?><?php echo e(!empty($scope['draw_id']) ? ' · Selected draw' : ' · All draws'); ?><?php echo e(!empty($scope['venue_id']) ? ' · Selected venue' : ' · All venues'); ?></p></div><a class="btn btn-outline-primary" href="<?php echo e(route('backend.event-venue-schedule.calendar', ['event'=>$event->id]+$scope)); ?>">Back to saved schedule</a></div>
  <p class="small text-muted">This audit reads saved matches. It does not save, reschedule, publish or hide anything.</p>
  <div class="card card-body mb-3"><div class="d-flex flex-wrap gap-4"><strong><?php echo e($report['checked']); ?> saved matches checked in this view</strong><span class="text-danger"><?php echo e($report['errors']); ?> errors</span><span class="text-warning"><?php echo e($report['warnings']); ?> warnings</span></div><p class="small text-muted mt-2 mb-0"><?php echo e($report['compared_event_matches']); ?> event bookings compared · <?php echo e($report['external_bookings']); ?> nearby outside-event bookings compared · Rest <?php echo e($report['rest_minutes']); ?> minutes · Court turnaround <?php echo e($report['court_gap_minutes']); ?> minutes.</p></div>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($report['unscheduled']): ?><div class="alert alert-warning"><?php echo e($report['unscheduled']); ?> eligible unfinished matches remain undated in the selected draw or event. Undated matches cannot be assigned to a day or venue filter.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($report['incomplete']): ?><div class="alert alert-warning">The audit is inconclusive. <?php echo e($report['coverage']); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$report['incomplete'] && !$report['errors'] && !$report['warnings']): ?><div class="alert alert-info">No issues were detected among the checked saved bookings within this audit's coverage.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $report['issues']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $issue): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="card mb-2 border-start border-3 <?php echo e($issue['severity']==='error'?'border-danger':'border-warning'); ?>"><div class="card-body"><strong><?php echo e(ucfirst($issue['severity'])); ?> · <?php echo e($issue['message']); ?></strong><div class="d-flex flex-wrap gap-2 mt-2"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $issue['matches']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $match): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="btn btn-sm btn-outline-primary" href="<?php echo e($match['url']); ?>"><?php echo e($match['label']); ?> · <?php echo e($match['time']); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($issue['external']): ?><p class="small text-muted mt-2 mb-0">This finding also involves an occupied slot outside this event. Its private match details are omitted.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($report['omitted_issues']): ?><div class="alert alert-warning"><?php echo e($report['omitted_issues']); ?> additional findings are included in the totals. Only the first 200 findings are displayed; narrow the day, venue or draw filter to review them.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <p class="small text-muted mt-3"><?php echo e($report['coverage']); ?></p>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\schedule\schedule-audit.blade.php ENDPATH**/ ?>