
<?php $__env->startSection('title','Review series emails'); ?>
<?php $__env->startSection('content'); ?>
<div data-mail-review><h1 class="h3"><?php echo e($series->name); ?> - review series emails</h1>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = ['success'=>'success','warning'=>'warning','error'=>'danger','info'=>'info']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $flash=>$tone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session($flash)): ?><div class="alert alert-<?php echo e($tone); ?>" role="status"><?php echo e(session($flash)); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger" role="alert"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<p><strong><?php echo e($emailCount); ?> event messages</strong> to <strong><?php echo e($uniqueCount); ?> unique email addresses</strong> across <?php echo e($batches->count()); ?> events.</p>
<div class="alert alert-info">One message is prepared per event. A recipient registered in multiple events receives a separate message for each event. Each preview below identifies its event. No emails are queued until you approve this entire intent.</div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $batches; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $batch): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><section class="card card-body mb-4"><h2 class="h4"><?php echo e($batch->event->name); ?></h2><p><?php echo e(count($batch->recipients)); ?> messages · Sender <?php echo e($batch->options['from_name']); ?> · Reply to <?php echo e($batch->options['reply_to']); ?></p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($batch->issues): ?><div class="alert alert-warning"><strong>Excluded missing contacts</strong><ul><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $batch->issues; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $issue): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($issue); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></ul></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php echo $__env->make('backend.partials.email-sample', ['mailRecipients' => $batch->recipients, 'mailSender' => $batch->options], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($batch->approved_at): ?><a href="<?php echo e(route('backend.event-communications.index',['event'=>$batch->event_id,'batch'=>$batch->id,'report_scope'=>'batch'])); ?>">Open this event's send report</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</section><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$batches->every(fn($batch)=>$batch->approved_at)): ?><form method="post" action="<?php echo e(route('series.email.approve',$series)); ?>"><?php echo csrf_field(); ?><input type="hidden" name="intent" value="<?php echo e($intent); ?>">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($batches->contains(fn($batch)=>!empty($batch->issues))): ?><label class="d-block mb-3"><input type="checkbox" name="acknowledge_missing" value="1" required> I acknowledge the excluded missing contacts for every event.</label><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<label class="d-block mb-3"><input type="checkbox" name="confirmed" value="1" required> I reviewed these exact recipients, event messages and sender details and approve this intent.</label><button class="btn btn-primary">Approve <?php echo e($emailCount); ?> event messages</button>
</form><?php else: ?><p>This intent was already approved. Use the event reports above to review actual queue and delivery outcomes.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<a class="btn btn-outline-secondary mt-3" href="<?php echo e(route('series.show',$series)); ?>">Return to series and start a new send intent</a>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\series\email-review.blade.php ENDPATH**/ ?>