<div class="mail-report-list"><div class="mail-report-row mail-report-head"><div>Recipient</div><div>Subject / type</div><div>Outcome</div><div>Recorded</div><div>Action</div></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $sendRecipients; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $mail): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>

<?php
    $reportSubject = $mail->history_subject ?? ($reportEvent ? \App\Services\EventMailLogService::subject($mail) : 'Subject not recorded');
    [$tone,$label] = match(true) {
        $mail->status==='sent' && $mail->evidence_status==='server_accepted' && $mail->accepted_at => ['success','Server accepted'],
        $mail->status==='sent' && $mail->evidence_status==='sandbox_accepted' && $mail->accepted_at => ['secondary','Sandbox accepted'],
        $mail->status==='sent' => ['secondary','Sent - evidence unverified'],
        $mail->status==='acceptance_unknown' => ['warning','Acceptance uncertain'],
        $mail->status==='failed' => ['danger','Failed'],
        $mail->status==='skipped' => ['secondary','Excluded'],
        default => ['primary',$mail->delivery_status_label],
    };
?>
<article class="mail-report-row"><div><strong><?php echo e($mail->recipient_name ?: $mail->recipient_email); ?></strong><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($mail->recipient_name): ?><div class="mail-report-secondary"><?php echo e($mail->recipient_email); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><div><strong><?php echo e($reportSubject); ?></strong><div class="mail-report-secondary"><?php echo e(\App\Services\SuperAdminMailHistory::typeLabel($mail->mail_type)); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(in_array(data_get($mail->payload,'recipient_kind'),['admin_copy','sender_copy'])): ?> · Copy <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><div><span class="badge bg-label-<?php echo e($tone); ?> <?php if($tone==='secondary'): ?> mail-report-neutral <?php endif; ?>"><?php echo e($label); ?></span><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($mail->status==='failed'): ?><div class="mail-report-secondary mt-1"><?php echo e(\App\Services\EventMailLogService::explanation($mail) ?: 'Review this failed attempt before retrying.'); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><div class="mail-report-date"><?php echo e($mail->created_at?->format('d M Y')); ?><div class="mail-report-secondary"><?php echo e($mail->created_at?->format('H:i')); ?> SAST</div></div><div class="mail-report-action"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($reportEvent): ?><a class="btn btn-outline-primary" href="<?php echo e(route('backend.event-mail-log.show',[$reportEvent,$mail])); ?>">Open</a>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($mail->status==='failed' && !$mail->sent_at && !$mail->accepted_at): ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(in_array($mail->mail_type,['team_selection_invitation','interprovincial_trial_invitation']) || (data_get($mail->payload,'event_communication_batch_id') && \App\Models\EventCommunicationBatch::whereKey(data_get($mail->payload,'event_communication_batch_id'))->where('event_id',$reportEvent->id)->where('created_by',auth()->id())->exists())): ?>
<form method="post" action="<?php echo e(route('backend.event-communications.retry-preview',[$reportEvent,$mail])); ?>" data-mail-launch><?php echo csrf_field(); ?><button class="btn btn-outline-primary mt-2">Review retry</button></form>
<?php elseif($reportEvent->isInterprovincialTrials() && data_get($mail->payload,'preview_id')): ?>
<details class="mt-2"><summary>Review retry</summary><strong><?php echo e(data_get($mail->payload,'subject')); ?></strong><pre style="white-space:pre-wrap;overflow-wrap:anywhere"><?php echo e(html_entity_decode(strip_tags(data_get($mail->payload,'body','')), ENT_QUOTES | ENT_HTML5, 'UTF-8')); ?></pre><form method="post" action="<?php echo e(route('backend.interprovincial-trials.communications.retry',[$reportEvent,$mail])); ?>"><?php echo csrf_field(); ?><label><input type="checkbox" name="approved_retry" value="1" required> I reviewed and approve this exact recipient and message.</label><button class="btn btn-outline-primary mt-2">Approve retry</button></form></details>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php else: ?><span class="mail-report-secondary">Metadata only</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></article>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="p-3">No recipients match these filters.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($sendRecipients->hasPages()): ?><div class="mt-3" data-send-pagination><?php echo e($sendRecipients->links('pagination::bootstrap-5')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php /**PATH C:\wamp64\www\ct\resources\views\backend\partials\mail-send-recipients.blade.php ENDPATH**/ ?>