
<?php $__env->startSection('title', 'Saved schedule – '.$event->name); ?>
<?php $__env->startSection('page-style'); ?><style>[data-saved-calendar] nav a { flex-shrink:0; }</style><?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?>
<div class="container-xxl py-3" data-saved-calendar>
  <div class="d-flex flex-wrap justify-content-between gap-3 mb-3"><div><h3 class="mb-1">Saved schedule</h3><p class="text-muted mb-0"><?php echo e($event->name); ?> · Add batches across the weekend. Saved changes stay private until you publish them.</p></div><div class="d-flex flex-wrap gap-2 align-self-start"><a class="btn btn-outline-primary" href="<?php echo e(route('headOffice.show', $event)); ?>">Back to event dashboard</a><a class="btn btn-primary" href="<?php echo e(route('backend.event-venue-schedule.index', $event)); ?>">Schedule more matches</a></div></div>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <nav class="d-flex gap-2 overflow-auto pb-2 mb-3" aria-label="Schedule days">
    <a class="btn text-nowrap <?php echo e($date === 'all' ? 'btn-primary' : 'btn-outline-primary'); ?>" href="<?php echo e(route('backend.event-venue-schedule.calendar',['event'=>$event->id]+array_replace($scope,['date'=>'all']))); ?>">All days</a>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $days; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $day => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a class="btn text-nowrap <?php echo e($day === $date ? 'btn-primary' : 'btn-outline-primary'); ?>" href="<?php echo e(route('backend.event-venue-schedule.calendar', ['event'=>$event->id]+array_replace($scope,['date'=>$day]))); ?>"><?php echo e(\Carbon\Carbon::parse($day)->format('D j M')); ?> <span class="badge bg-white text-primary ms-1"><?php echo e($count); ?></span></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><span class="text-muted">No saved match times yet.</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  </nav>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($date === 'all'): ?>
    <div class="mb-3">
      <h5 class="mb-1">Publish one day at a time</h5>
      <p class="small text-muted mb-2">Each button publishes that whole day's saved times across all venues and draws, including any updates. Other days keep their current state, except moved matches replace their previous public times. Draws and team ties must also be published for players to see their times.</p>
      <div class="row g-3">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $days; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $day => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
          <?php ($savedCount = (int) ($dailySavedCounts[$day] ?? 0)); ?>
          <div class="col-12 col-md-6 col-lg-4"><div class="card h-100"><div class="card-body">
            <h6 class="mb-1">Day <?php echo e($loop->iteration); ?> · <?php echo e(\Carbon\Carbon::parse($day)->format('D j M Y')); ?></h6>
            <div class="small mb-1"><?php echo e($savedCount); ?> saved <?php echo e(Str::plural('match', $savedCount)); ?></div>
            <div class="small text-muted mb-3">Whole day · all venues and draws</div>
            <div class="d-flex flex-wrap gap-2 align-items-center">
              <a class="btn btn-sm btn-outline-primary" href="<?php echo e(route('backend.event-venue-schedule.calendar', ['event' => $event->id, 'date' => $day])); ?>">Review day</a>
              <form method="post" action="<?php echo e(route('backend.event-venue-schedule.calendar.publish', $event)); ?>">
                <?php echo csrf_field(); ?>
                <input type="hidden" name="revision" value="<?php echo e($revision); ?>">
                <input type="hidden" name="date" value="<?php echo e($day); ?>">
                <button type="submit" class="btn btn-sm btn-success" <?php if($savedCount === 0): echo 'disabled'; endif; ?>>Publish Day <?php echo e($loop->iteration); ?></button>
              </form>
            </div>
          </div></div></div>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      </div>
    </div>
  <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <form method="get" class="card card-body mb-3"><div class="row g-3 align-items-end">
    <div class="col-12 col-md-3"><label class="form-label" for="calendar-date">Day</label><input class="form-control" id="calendar-date" type="date" name="date" value="<?php echo e($date === 'all' ? '' : $date); ?>"></div>
    <div class="col-12 col-md-4"><label class="form-label" for="calendar-venue">Venue</label><select class="form-select" id="calendar-venue" name="venue_id"><option value="">All venues</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $venues; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $venue): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($venue->id); ?>" <?php if((int)($scope['venue_id']??0)===$venue->id): echo 'selected'; endif; ?>><?php echo e($venue->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
    <div class="col-12 col-md-3"><label class="form-label" for="calendar-draw">Draw / age group</label><select class="form-select" id="calendar-draw" name="draw_id"><option value="">All draws</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $draws; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $draw): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($draw->id); ?>" <?php if((int)($scope['draw_id']??0)===$draw->id): echo 'selected'; endif; ?>><?php echo e($draw->drawName); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
    <div class="col-12 col-md-2"><button class="btn btn-outline-primary w-100">Show schedule</button></div>
  </div></form>
  <div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-3"><p class="text-muted mb-0"><?php echo e($unscheduledCount); ?> matches remain without a day or time<?php echo e(!empty($scope['draw_id']) ? ' in this draw' : ' across the event'); ?>.</p><a class="btn btn-outline-primary" href="<?php echo e(route('backend.event-venue-schedule.calendar.audit', ['event'=>$event->id]+$scope)); ?>">Run schedule audit</a></div>
  <div class="card mb-3"><div class="card-body d-flex flex-wrap align-items-center justify-content-between gap-3"><div><strong><?php echo e($rows->count()); ?> saved matches on this view</strong><div class="small text-muted"><?php echo e($rows->where('publication_state','Published')->count()); ?> published times · <?php echo e($rows->where('publication_state','Private')->count()); ?> private · <?php echo e($rows->where('publication_state','Updates private')->count()); ?> with private updates · <?php echo e($rows->where('publication_state','Not publicly visible')->count()); ?> not publicly visible</div><div class="small text-muted">Draws and team ties must also be published before players can see their times.</div></div><div class="d-flex flex-wrap gap-2">
    <a class="btn btn-outline-secondary" href="<?php echo e(route('backend.event-venue-schedule.calendar.preview',['event'=>$event->id]+$scope)); ?>">Preview public schedule</a>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($date !== 'all'): ?>
      <form method="post" action="<?php echo e(route('backend.event-venue-schedule.calendar.publish',$event)); ?>"><?php echo csrf_field(); ?><input type="hidden" name="revision" value="<?php echo e($revision); ?>"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $scope; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><input type="hidden" name="<?php echo e($key); ?>" value="<?php echo e($value); ?>"><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><button class="btn btn-success"><?php echo e($rows->where('publication_state','Updates private')->isNotEmpty() ? 'Publish updates for this day' : 'Publish this day'); ?></button></form>
      <form method="post" action="<?php echo e(route('backend.event-venue-schedule.calendar.hide',$event)); ?>"><?php echo csrf_field(); ?><input type="hidden" name="revision" value="<?php echo e($revision); ?>"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $scope; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><input type="hidden" name="<?php echo e($key); ?>" value="<?php echo e($value); ?>"><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><button class="btn btn-outline-danger">Hide public times</button></form>
    <?php else: ?><span class="small text-muted align-self-center">Choose a day to publish all venues or filter to a venue and draw.</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  </div></div></div>
  <p class="small text-muted d-md-none mb-2">Swipe the match table sideways to see every column.</p>
  <div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Time</th><th>Venue / court</th><th>Draw / match</th><th>Participants</th><th>Public visibility</th></tr></thead><tbody>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $rows; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr id="match-<?php echo e(str_replace(':','-',$row['fixture_key'])); ?>"><td class="text-nowrap"><?php echo e($date === 'all' ? substr($row['scheduled_at'],0,16) : substr($row['scheduled_at'],11,5)); ?></td><td><?php echo e($row['venue_name']); ?><div class="small text-muted">Court <?php echo e($row['court']); ?></div></td><td><?php echo e($row['draw_name']); ?><div class="small text-muted"><?php echo e(ucfirst($row['fixture_kind'])); ?> match <?php echo e($row['fixture_id']); ?></div></td><td><?php if (isset($component)) { $__componentOriginald032f6f37ccfe5a3c340f472d904fe2e = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginald032f6f37ccfe5a3c340f472d904fe2e = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.scheduled-participants','data' => ['row' => $row]] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('scheduled-participants'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['row' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute($row)]); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginald032f6f37ccfe5a3c340f472d904fe2e)): ?>
<?php $attributes = $__attributesOriginald032f6f37ccfe5a3c340f472d904fe2e; ?>
<?php unset($__attributesOriginald032f6f37ccfe5a3c340f472d904fe2e); ?>
<?php endif; ?>
<?php if (isset($__componentOriginald032f6f37ccfe5a3c340f472d904fe2e)): ?>
<?php $component = $__componentOriginald032f6f37ccfe5a3c340f472d904fe2e; ?>
<?php unset($__componentOriginald032f6f37ccfe5a3c340f472d904fe2e); ?>
<?php endif; ?></td><td><span class="badge <?php echo e($row['publication_state']==='Published'?'bg-label-success':'bg-label-warning'); ?>"><?php echo e($row['publication_state']); ?></span></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="5" class="text-muted py-4">No saved matches match these filters. Schedule another batch to add matches here.</td></tr><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  </tbody></table></div></div>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($retained->isNotEmpty()): ?><div class="alert alert-info mt-3"><strong>Previous public times are still visible</strong><p class="mb-2 small">These match times were moved or removed privately. Publish updates or hide this day and venue to change what players see.</p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $retained; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="small"><?php echo e($row['draw_name']); ?> · match <?php echo e($row['fixture_id']); ?> · <?php echo e($date === 'all' ? substr($row['scheduled_at'],0,16) : substr($row['scheduled_at'],11,5)); ?> · <?php echo e($row['venue_name']); ?> / <?php echo e($row['court']); ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\schedule\saved-calendar.blade.php ENDPATH**/ ?>