<?php $__env->startSection('title','Participation refund'); ?>
<?php $__env->startSection('content'); ?>
<div class="container py-4"><div class="card card-body mx-auto" style="max-width:760px"><h4>Participation refund — <?php echo e($participation->player->full_name); ?></h4><p><?php echo e($event->name); ?></p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<p>Original amount paid: R<?php echo e(number_format($participation->order->total_amount,2)); ?>. Existing event withdrawal fee of 10% applies. Withdraw before the regional participation payment deadline to qualify.</p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($participation->order->refund_status==='completed'): ?><div class="alert alert-success">Refund completed: R<?php echo e(number_format($participation->order->refund_net,2)); ?>.</div>
<?php elseif(!$participation->order->withdrawn_at): ?><p>Withdraw the participation before requesting a refund.</p>
<?php else: ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($participation->order->refund_status==='pending'): ?><div class="alert alert-info">Refund pending: R<?php echo e(number_format($participation->order->refund_net,2)); ?>.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<form method="post" action="<?php echo e(route('interprovincial-trials.participation.request-refund',[$event,$participation])); ?>"><?php echo csrf_field(); ?><label class="form-label">Refund method</label><select name="method" class="form-select mb-3"><option value="bank">Manual bank refund</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($participation->order->payfast_paid && $participation->order->payfast_pf_payment_id): ?><option value="payfast">PayFast refund to original payment</option><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = ['refund_account_name'=>'Account holder','refund_bank_name'=>'Bank','refund_account_number'=>'Account number','refund_branch_code'=>'Branch code']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><label class="form-label"><?php echo e($label); ?></label><input name="<?php echo e($field); ?>" class="form-control mb-2" required value="<?php echo e(old($field,$participation->order->$field)); ?>"><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<label class="form-label">Account type</label><select name="refund_account_type" class="form-select mb-3"><option value="current">Current</option><option value="savings">Savings</option></select><button class="btn btn-primary">Request refund</button></form>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<a href="<?php echo e(route('events.show',$event)); ?>" class="mt-3">Back to event</a></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts/layoutMaster', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\frontend\interprovincial-trials\participation-refund.blade.php ENDPATH**/ ?>