<?php $__env->startSection('title', 'Platteland team invitation'); ?>
<?php $__env->startSection('content'); ?>
<?php ($event = $invitation->selectionImport?->event); ?>
<?php ($responseDeadline = $invitation->effectiveResponseDeadline()); ?>
<?php ($paymentDeadline = $invitation->effectivePaymentDeadline()); ?>
<div class="container-xxl flex-grow-1 container-p-y"><div class="row justify-content-center"><div class="col-xl-8 col-lg-9"><div class="card border-primary shadow-sm">
  <div class="card-header text-center py-4"><span class="badge bg-label-primary mb-2">Regional team selection</span><h4 class="mb-1">Platteland team invitation</h4><p class="text-muted mb-0"><?php echo e($event?->name); ?></p></div>
  <div class="card-body p-4 p-lg-5"><h5>Hello <?php echo e($invitation->player?->full_name); ?>,</h5>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($invitation->selectionImport?->email_message): ?><p><?php echo nl2br(e($invitation->selectionImport->email_message)); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <p>You have been selected to represent <strong><?php echo e($invitation->region?->region_name); ?></strong>.</p>
    <div class="alert alert-primary d-flex flex-column gap-1"><strong><?php echo e($invitation->team?->name); ?></strong><span>Ranking position: <?php echo e($invitation->ranking_position); ?></span><span>Playing order: <?php echo e($invitation->roster_rank); ?></span></div>
    <div class="row g-2 mb-4">
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event?->start_date): ?><div class="col-sm-6"><div class="border rounded p-3 h-100"><small class="text-muted d-block">Event dates</small><strong><?php echo e($event->start_date->format('d M Y')); ?><?php echo e($event->end_date && !$event->end_date->equalTo($event->start_date) ? ' – '.$event->end_date->format('d M Y') : ''); ?></strong></div></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <div class="col-sm-6"><div class="border rounded p-3 h-100"><small class="text-muted d-block">Entry fee</small><strong>R<?php echo e(number_format((float) $event?->entryFee, 2)); ?></strong></div></div>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($responseDeadline): ?><div class="col-sm-6"><div class="border rounded p-3 h-100"><small class="text-muted d-block">Respond by</small><strong><?php echo e($responseDeadline->format('d M Y H:i')); ?></strong></div></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($paymentDeadline): ?><div class="col-sm-6"><div class="border rounded p-3 h-100"><small class="text-muted d-block">Payment deadline</small><strong><?php echo e($paymentDeadline->format('d M Y H:i')); ?></strong></div></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </div>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($invitation->selectionImport?->event_information): ?><div class="alert alert-warning"><strong>Event information</strong><div class="mt-1"><?php echo nl2br(e($invitation->selectionImport->event_information)); ?></div></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($regionAnnouncements->isNotEmpty()): ?>
      <div class="mb-4"><h5><?php echo e($invitation->region?->region_name); ?> announcements</h5><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $regionAnnouncements; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $announcement): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="border rounded p-3 mb-2"><strong><?php echo e($announcement->title); ?></strong><div class="mt-1"><?php echo $announcement->message; ?></div><small class="text-muted"><?php echo e($announcement->created_at->format('d M Y H:i')); ?></small></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($invitation->status === \App\Models\TeamSelectionInvitation::INVITED): ?>
      <p>Register and complete payment to play. Your team place is confirmed after payment has been verified.</p><div class="d-flex flex-wrap gap-2"><form method="POST" action="<?php echo e(route('team-selection.invitations.accept', $invitation)); ?>"><?php echo csrf_field(); ?><button class="btn btn-success btn-lg"><i class="ti ti-credit-card me-1"></i>Register and pay</button></form><button class="btn btn-outline-danger btn-lg" data-bs-toggle="modal" data-bs-target="#decline-team-invitation">I am unavailable</button></div>
    <?php elseif($invitation->status === \App\Models\TeamSelectionInvitation::ACCEPTED_PENDING_PAYMENT): ?>
      <div class="alert alert-warning"><strong>Your place is not confirmed yet.</strong> Complete payment before the deadline, or decline so the reserve can be invited.</div><div class="d-flex flex-wrap gap-2"><a class="btn btn-success btn-lg" href="<?php echo e(route('team.payment.payfast', [$invitation->team_id,$invitation->player_id,$invitation->event_id])); ?>"><i class="ti ti-credit-card me-1"></i>Continue payment</a><button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#decline-team-invitation">Decline invitation</button></div>
    <?php elseif($invitation->status === \App\Models\TeamSelectionInvitation::PAID_CONFIRMED): ?>
      <div class="alert alert-success"><i class="ti ti-circle-check me-1"></i><strong>Registration and payment confirmed.</strong> Your team place is secured.</div>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($canOrderClothing): ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($invitation->clothing_decision === 'not_required'): ?>
          <div class="alert alert-secondary mb-0"><i class="ti ti-shirt-off me-1"></i>No clothing required has been recorded.</div>
        <?php else: ?>
          <div class="d-flex flex-wrap gap-2">
            <a class="btn btn-outline-primary" href="<?php echo e(route('team-selection.invitations.clothing', $invitation)); ?>"><i class="ti ti-shirt me-1"></i>Order optional clothing</a>
            <form method="POST" action="<?php echo e(route('team-selection.invitations.clothing-decision', $invitation)); ?>" onsubmit="return confirm('Confirm that no clothing is required for this player?');"><?php echo csrf_field(); ?><input type="hidden" name="decision" value="not_required"><button class="btn btn-outline-secondary"><i class="ti ti-shirt-off me-1"></i>No clothing required</button></form>
          </div>
        <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($clothingOrders->isNotEmpty()): ?><div class="mt-3"><strong>Clothing orders</strong><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $clothingOrders; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $order): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="small text-muted">Order #<?php echo e($order->id); ?> · R<?php echo e(number_format((float)$order->total, 2)); ?> · <?php echo e($order->pay_status ? 'Paid' : 'Payment pending'); ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <?php else: ?><div class="alert alert-secondary mb-0">This invitation is <?php echo e(str_replace('_',' ',$invitation->status)); ?>.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  </div>
</div></div></div></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(in_array($invitation->status, [\App\Models\TeamSelectionInvitation::INVITED, \App\Models\TeamSelectionInvitation::ACCEPTED_PENDING_PAYMENT], true)): ?>
<div class="modal fade" id="decline-team-invitation" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="<?php echo e(route('team-selection.invitations.decline', $invitation)); ?>" class="modal-content"><?php echo csrf_field(); ?><div class="modal-header"><h5 class="modal-title">Decline invitation?</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p>The place will be released and the next reserve may be invited.</p><label class="form-label">Reason (optional)</label><textarea name="reason" maxlength="1000" class="form-control" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Keep invitation</button><button class="btn btn-danger">Confirm decline</button></div></form></div></div>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('page-script'); ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(request('action') === 'decline'): ?><script>document.addEventListener('DOMContentLoaded',()=>{const el=document.getElementById('decline-team-invitation');if(el&&window.bootstrap) bootstrap.Modal.getOrCreateInstance(el).show();});</script><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts/contentNavbarLayout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\frontend\team-selection\show.blade.php ENDPATH**/ ?>