
<?php $__env->startSection('title','Regional team participation payment'); ?>
<?php $__env->startSection('content'); ?>
<div class="container py-4"><div class="card card-body mx-auto" style="max-width:760px"><h4><?php echo e($event->name); ?> — team participation</h4><p><?php echo e($participation->player->full_name); ?> — Team <?php echo e($participation->slot->tier); ?></p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<p>Participation fee: <strong>R<?php echo e(number_format($order->total_amount,2)); ?></strong></p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($participation->isPaid()): ?><div class="alert alert-success">Payment confirmed.</div><form method="post" action="<?php echo e(route('interprovincial-trials.participation.withdraw',[$event,$participation])); ?>"><?php echo csrf_field(); ?><button class="btn btn-outline-warning">Withdraw participation</button></form>
<?php elseif($payfast): ?><p>Your checkout is prepared for secure payment.</p><?php echo $payfast->getForm(); ?><button type="submit" form="payfastForm" class="btn btn-primary">Continue to PayFast</button>
<?php elseif($order->payfast_handed_off_at): ?><div class="alert alert-info">PayFast payment is awaiting verification. Your checkout cannot be changed while it is resolving.</div>
<?php else: ?>
<form method="post" action="<?php echo e(route('interprovincial-trials.participation.payfast',[$event,$participation])); ?>"><?php echo csrf_field(); ?><button class="btn btn-primary mb-3">Pay online</button></form>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(filled($programme?->bank_details)): ?><h5>Pay by EFT</h5><pre style="white-space:pre-wrap"><?php echo e($programme->bank_details); ?></pre><p>Upload proof after making payment. An admin verifies it before payment is confirmed.</p><form method="post" enctype="multipart/form-data" action="<?php echo e(route('interprovincial-trials.participation.proof',[$event,$participation])); ?>"><?php echo csrf_field(); ?><label class="form-label">Payment proof (PDF/JPEG/PNG, maximum 5 MB)</label><input class="form-control mb-2" type="file" name="proof" accept="application/pdf,image/jpeg,image/png" required><button class="btn btn-outline-primary">Upload proof</button></form><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<form method="post" action="<?php echo e(route('interprovincial-trials.participation.cancel',[$event,$participation])); ?>" class="mt-3"><?php echo csrf_field(); ?><button class="btn btn-outline-secondary">Cancel unpaid checkout</button></form>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($proofs->isNotEmpty()): ?><h5 class="mt-3">Submitted proofs</h5><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $proofs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $proof): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><p><a href="<?php echo e(route('interprovincial-trials.participation.download',[$event,$proof])); ?>">Proof <?php echo e($proof->created_at); ?></a> — <?php echo e($proof->status); ?></p><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><?php endif; ?>
<a href="<?php echo e(route('events.show',$event)); ?>" class="mt-3">Back to event</a></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts/layoutMaster', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\frontend\interprovincial-trials\participation.blade.php ENDPATH**/ ?>