
<?php $__env->startSection('title','My email issues'); ?>
<?php $__env->startSection('content'); ?>
<?php echo $__env->make('backend.event.mail-log.feedback', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<h1 class="h3">My email issues</h1><p>Persistent alerts for your event emails. Acknowledging an alert does not resend or change the email outcome.</p>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $visible; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="card mb-3"><div class="card-body" style="overflow-wrap:anywhere"><h2 class="h6"><?php echo e($item['event'] ? $item['event']->name : 'Your email attempt'); ?></h2><p><?php echo e(\Illuminate\Support\Str::headline($item['issue']->kind)); ?> · Attempt <?php echo e($item['issue']->attempt_number); ?> - <?php echo e($item['issue']->created_at->format('d M Y H:i')); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item['log']): ?> - <?php echo e($item['log']->recipient_email); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item['log']): ?><a class="btn btn-outline-primary" href="<?php echo e(route('backend.event-mail-log.show',[$item['event'],$item['log']])); ?>">Review email record</a><?php else: ?><p>Private event details require current event-management access.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><?php if(!$item['issue']->read_at): ?><form class="d-inline" method="post" action="<?php echo e(route('backend.event-mail-log.acknowledge',[$item['issue']->event_id,$item['issue']])); ?>"><?php echo csrf_field(); ?><button class="btn btn-outline-secondary">Acknowledge</button></form><?php else: ?><span class="text-muted">Acknowledged</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p>No email issues.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php echo e($issues->links('pagination::bootstrap-5')); ?>

<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts/layoutMaster', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\event\mail-log\issues.blade.php ENDPATH**/ ?>