<details class="result-rules">
  <summary>How the ranking works</summary>
  <p>Roster bands come first: 1–2, then 3–4, 5–6, and 7–8. A player remains in their band even with zero wins. Within each band, points equal completed match wins multiplied by its weight: 100, 35, 12, or 2. Equal points are ordered by completed-match sets won minus sets lost. If tied players all come from the same team, the higher roster position comes first. Players from different teams are compared by direct wins when every tied pair has the same nonzero number of counted matches. Unresolved ties require review at the selection cutoff. Candidate regions choose players; excluded result regions remove entire matches involving either side. Adjacent-band comparisons support manual review and do not promote players automatically. Explain departures from the suggestions before saving a draft.</p>
</details>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($ranking->isEmpty()): ?>
  <div class="result-empty" role="status"><i class="ti ti-scoreboard" aria-hidden="true"></i><strong>No completed singles results</strong><p>Check the regions and match formats in Setup, or choose another age group. Incomplete matches and doubles are excluded.</p></div>
<?php else: ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($ranking->contains('cutoff_tie', true)): ?>
    <div class="result-review-notice" role="status"><strong>Review the tenth-place tie.</strong> Both points and set difference are equal. Record a selection decision and reasons.</div>
  <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <ol class="result-player-list" aria-label="Suggested top 10 and player ranking">
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $ranking; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $player): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
    <?php $wonAllCountedBandMatches = !$player['band_attribution_uncertain'] && $player['own_band_record']['wins'] > 0 && $player['own_band_record']['losses'] === 0; ?>
    <li class="<?php echo \Illuminate\Support\Arr::toCssClasses(['result-player-card', 'result-player-card-lost-all' => $player['lost_all_counted_band_matches'], 'result-player-card-won-all' => $wonAllCountedBandMatches]); ?>">
      <div class="result-player-heading">
        <label class="result-player-select"><input type="checkbox" class="form-check-input" data-selection-player value="<?php echo e($player['id']); ?>" <?php echo e($player['suggested'] ? 'checked' : ''); ?>><span class="visually-hidden">Select <?php echo e($player['name']); ?></span></label>
        <span class="result-position"><?php echo e($player['position']); ?></span>
        <div class="result-player-identity"><strong><?php echo e($player['name']); ?></strong><span><?php echo e($player['region']); ?> · <?php echo e(implode(', ', $player['teams'])); ?></span><span>Roster <?php echo e(implode(', ', $player['ranks'])); ?> · Band <?php echo e($player['band']); ?> · <?php echo e($player['wins']); ?>W / <?php echo e($player['losses']); ?>L</span></div>
        <div class="result-player-points"><strong><?php echo e($player['points']); ?></strong><span>points</span></div>
      </div>
      <div class="result-player-tags">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($player['suggested']): ?><span class="result-tag result-tag-selected">Suggested top 10</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($player['cutoff_tie']): ?><span class="result-tag result-tag-review">Review cutoff tie</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($player['higher_rank_wins']): ?><span class="result-tag"><?php echo e($player['higher_rank_wins']); ?> win(s) over higher-rostered opponents</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($player['lost_all_counted_band_matches']): ?><span class="result-tag result-tag-review">Review: lost all counted matches in Band <?php echo e($player['band']); ?> · 0W / <?php echo e($player['own_band_record']['losses']); ?>L</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($wonAllCountedBandMatches): ?><span class="result-tag result-tag-selected">Won all counted band matches · <?php echo e($player['own_band_record']['wins']); ?>W / 0L</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      </div>
      <dl class="result-metrics">
        <div><dt>Points per win</dt><dd><?php echo e($player['points_per_win']); ?></dd></div>
        <div><dt>Singles wins</dt><dd><?php echo e($player['singles_wins']); ?></dd></div>
        <div><dt>Reverse wins</dt><dd><?php echo e($player['reverse_singles_wins']); ?></dd></div>
        <div><dt>Match wins</dt><dd><?php echo e($player['wins']); ?></dd></div>
        <div><dt>Sets won / lost</dt><dd><?php echo e($player['sets_won']); ?> / <?php echo e($player['sets_lost']); ?></dd></div>
        <div><dt>Set difference</dt><dd><?php echo e($player['set_difference'] > 0 ? '+' : ''); ?><?php echo e($player['set_difference']); ?></dd></div>
      </dl>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($player['head_to_head']['tied_players'] > 1 && !$player['same_team_tiebreak']): ?>
        <p class="result-review-notice">Head-to-head among tied players: <?php echo e($player['head_to_head']['wins']); ?>W / <?php echo e($player['head_to_head']['losses']); ?>L. <?php echo e($player['head_to_head']['reason']); ?></p>
      <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <details class="result-review-notice result-review-details"><summary>Compare adjacent bands</summary><p>Direct records below use counted matches only. Overall records may involve different opponents and do not establish relative strength. These comparisons do not change the band order.</p>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $player['adjacent_band_comparisons']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $comparison): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
          <div class="result-review-records"><strong><?php echo e(ucfirst($comparison['direction'])); ?> Band <?php echo e($comparison['band']); ?></strong>
          <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($comparison['direct_matches']): ?>
            <span>Direct meetings: <?php echo e($comparison['direct_wins']); ?>W / <?php echo e($comparison['direct_losses']); ?>L · Sets <?php echo e($comparison['sets_won']); ?> / <?php echo e($comparison['sets_lost']); ?></span>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($comparison['direction'] === 'higher' && $comparison['direct_wins']): ?><strong>Review: <?php echo e($comparison['direct_wins']); ?> direct win(s) over the next higher band</strong><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $comparison['opponents']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $opponent): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span><?php echo e($opponent['name']); ?> · Roster <?php echo e(implode(', ', $opponent['ranks'])); ?> · <?php echo e($opponent['wins']); ?>W / <?php echo e($opponent['losses']); ?>L · Sets <?php echo e($opponent['sets_won']); ?> / <?php echo e($opponent['sets_lost']); ?> from this player's perspective</span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
          <?php else: ?><p>No direct meetings with this band in the counted matches.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
          <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $comparison['candidate_records']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $record): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span><?php echo e($record['name']); ?> · Roster <?php echo e(implode(', ', $record['ranks'])); ?> · Overall <?php echo e($record['wins']); ?>W / <?php echo e($record['losses']); ?>L · Sets <?php echo e($record['sets_won']); ?> / <?php echo e($record['sets_lost']); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
          </div>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      </details>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $player['cross_band_review']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $review): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <details class="result-review-notice result-review-details"><summary><strong>Review consecutive roster records</strong> · <?php echo e($review['team']); ?> · Ranks <?php echo e(implode(', ', $review['ranks'])); ?></summary><p>Each consecutive player has at least two completed matches and more wins than losses in this setup. Different opponents can affect these records; the band-first order is retained.</p><div class="result-review-records"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $review['records']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $rank => $record): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span>Rank <?php echo e($rank); ?>: <?php echo e($record['wins']); ?>W / <?php echo e($record['losses']); ?>L</span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></details>
      <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(count($player['ranks']) > 1): ?><p class="result-review-notice">Roster ranks differ across teams. Ranking uses rank <?php echo e($player['rank']); ?>; review before selection.<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($player['band_attribution_uncertain']): ?> Ranks span different bands, so the lost-all-in-band flag is withheld.<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <div class="result-player-disclosures">
        <details class="result-reason"><summary>Selection reason <span>Required for changes or cutoff ties</span></summary><label>Reason for <?php echo e($player['name']); ?><input class="form-control" type="text" maxlength="2000" data-selection-reason="<?php echo e($player['id']); ?>" placeholder="Record the results supporting your decision"></label></details>
        <details class="result-matches"><summary>Match results <span><?php echo e(count($player['matches'])); ?> completed</span></summary><ul>
          <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $player['matches']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $match): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <li><span class="result-match-outcome <?php echo e($match['won'] ? 'is-win' : 'is-loss'); ?>"><?php echo e($match['won'] ? 'Won' : 'Lost'); ?></span><div><strong><?php echo e($match['opponent']); ?></strong><span><?php echo e($match['region']); ?> · Roster <?php echo e($match['opponent_rank']); ?> · <?php echo e($match['format'] === 'reverse_singles' ? 'Reverse Singles' : 'Singles'); ?></span></div><span class="result-match-score">Home–away: <?php echo e($match['score']); ?></span></li>
          <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </ul></details>
      </div>
    </li>
  <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  </ol>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php /**PATH C:\wamp64\www\ct\resources\views\backend\adminPage\admin_show\_table\result-selection.blade.php ENDPATH**/ ?>