<?php $__env->startSection('title', 'Preview ranked-player import'); ?>

<?php $__env->startSection('content'); ?>
<div class="container-xxl flex-grow-1 container-p-y">
  <div class="d-flex justify-content-between align-items-start gap-2 mb-4"><div><h4 class="mb-1">Preview ranked-player import</h4><p class="text-muted mb-0"><?php echo e($source->region?->region_name); ?> · <?php echo e($source->series?->name); ?></p></div><a href="<?php echo e(route('backend.team-selection.index', $event)); ?>" class="btn btn-outline-secondary">Back to team selection</a></div>
  <div class="alert alert-info">Published ranking snapshot: <code><?php echo e($preview['run_id']); ?></code>. Confirming will fill each team with the available eligible players, up to its configured size, and add available reserves.</div>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $preview['warnings']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $warning): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="alert alert-danger py-2"><strong>Import blocked:</strong> <?php echo e($warning); ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $preview['notices']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $notice): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="alert alert-warning py-2"><strong>Incomplete roster:</strong> <?php echo e($notice); ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $preview['mappings']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $mapping): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
    <?php ($selectedCount = min($mapping['capacity'], $mapping['players']->count())); ?>
    <?php ($emptyCount = max(0, $mapping['capacity'] - $selectedCount)); ?>
    <?php ($availableReserves = max(0, $mapping['players']->count() - $mapping['capacity'])); ?>
    <div class="card mb-3"><div class="card-header"><h5 class="mb-0"><?php echo e($mapping['team']->name); ?></h5><span class="text-muted small"><?php echo e($mapping['capacity']); ?> team places · <?php echo e($selectedCount); ?> selected · <?php echo e($emptyCount); ?> empty · <?php echo e($availableReserves); ?> reserves available · <?php echo e($mapping['skipped_count']); ?> ineligible skipped</span></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Place</th><th>Player</th><th>Ranking</th><th>Points</th><th>Events played</th></tr></thead><tbody><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $mapping['players']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><span class="badge bg-label-<?php echo e($index < $mapping['capacity'] ? 'primary' : 'secondary'); ?>"><?php echo e($index < $mapping['capacity'] ? 'Team #'.($index+1) : 'Reserve '.($index-$mapping['capacity']+1)); ?></span></td><td><?php echo e($row->player?->full_name); ?></td><td>#<?php echo e($row->rank_position); ?></td><td><?php echo e($row->total_points); ?></td><td><?php echo e(data_get($row->meta_json, 'events_played', '—')); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php for($rank = $selectedCount + 1; $rank <= $mapping['capacity']; $rank++): ?><tr class="table-warning"><td><span class="badge bg-label-warning">Team #<?php echo e($rank); ?></span></td><td><em>Empty place</em></td><td>—</td><td>—</td><td>—</td></tr><?php endfor; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></tbody></table></div></div>
  <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <form method="POST" action="<?php echo e(route('backend.team-selection.import', [$event, $source])); ?>">
    <?php echo csrf_field(); ?>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($preview['notices']): ?>
      <div class="form-check border rounded p-3 ps-5 mb-3">
        <input class="form-check-input" type="checkbox" value="1" name="confirm_incomplete_rosters" id="confirm-incomplete-rosters" required>
        <label class="form-check-label" for="confirm-incomplete-rosters"><strong>I confirm these incomplete rosters.</strong> Import the available players and keep the remaining team and reserve places empty.</label>
      </div>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <button class="btn btn-primary" <?php echo e($preview['warnings'] ? 'disabled' : ''); ?>>Confirm and import available players</button>
  </form>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\team-selection\preview.blade.php ENDPATH**/ ?>