
<?php $__env->startSection('title', 'Order regional clothing'); ?>
<?php $__env->startSection('content'); ?>
<div class="container-xxl flex-grow-1 container-p-y"><div class="row justify-content-center"><div class="col-xl-8 col-lg-9">
  <div class="d-flex justify-content-between align-items-start gap-2 mb-3"><div><h4 class="mb-1">Optional regional clothing</h4><p class="text-muted mb-0"><?php echo e($invitation->region?->region_name); ?> · <?php echo e($invitation->player?->full_name); ?></p></div><a class="btn btn-outline-secondary" href="<?php echo e(route('team-selection.invitations.show', $invitation)); ?>">Back</a></div>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><ul class="mb-0"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></ul></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <form method="POST" action="<?php echo e(route('clothingOrder.store')); ?>" class="card shadow-sm" id="regional-clothing-form" data-payfast-percentage="<?php echo e($payfastSettings['percentage']); ?>" data-payfast-flat="<?php echo e($payfastSettings['flat']); ?>" data-payfast-vat="<?php echo e($payfastSettings['vat']); ?>"><?php echo csrf_field(); ?>
    <input type="hidden" name="event_id" value="<?php echo e($invitation->event_id); ?>"><input type="hidden" name="region_id" value="<?php echo e($invitation->region_id); ?>"><input type="hidden" name="player_id" value="<?php echo e($invitation->player_id); ?>"><input type="hidden" name="team_id" value="<?php echo e($invitation->team_id); ?>"><input type="hidden" name="request_token" value="<?php echo e($requestToken); ?>">
    <div class="card-body"><p>Select only the items you require. Clothing is paid separately from the event entry.</p><div class="d-grid gap-3">
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="border rounded p-3 clothing-line" data-price="<?php echo e((float)$item->price); ?>"><div class="form-check mb-2"><input class="form-check-input clothing-toggle" type="checkbox" id="clothing-<?php echo e($item->id); ?>"><label class="form-check-label fw-semibold" for="clothing-<?php echo e($item->id); ?>"><?php echo e($item->item_type_name); ?> · R<?php echo e(number_format((float)$item->customer_price, 2)); ?></label></div><div class="row g-2 clothing-options d-none"><div class="col-sm-7"><label class="form-label">Size</label><select class="form-select" name="items[<?php echo e($item->id); ?>][size]" disabled required><option value="">Choose size</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $item->sizes->sortBy('ordering'); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $size): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($size->id); ?>"><?php echo e($size->size); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div><div class="col-sm-5"><label class="form-label">Quantity</label><input class="form-control clothing-qty" type="number" name="items[<?php echo e($item->id); ?>][qty]" value="1" min="1" max="20" disabled required></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </div><div class="border-top mt-4 pt-3"><div class="d-flex justify-content-between fs-5"><strong>Total payable</strong><strong id="clothing-total">R0.00</strong></div></div></div>
    <div class="card-footer d-flex justify-content-end"><button class="btn btn-primary" id="clothing-submit" disabled>Continue to clothing payment</button></div>
  </form>
</div></div></div>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('page-script'); ?>
<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('regional-clothing-form'),total=document.getElementById('clothing-total'),submit=document.getElementById('clothing-submit');const feeFor=amount=>amount>0?Math.round((((amount*Number(form.dataset.payfastPercentage)/100)+Number(form.dataset.payfastFlat))*(1+Number(form.dataset.payfastVat)/100))*100)/100:0;const refresh=()=>{let amount=0,selected=0;form.querySelectorAll('.clothing-line').forEach(line=>{const checked=line.querySelector('.clothing-toggle').checked,options=line.querySelector('.clothing-options');options.classList.toggle('d-none',!checked);options.querySelectorAll('select,input').forEach(input=>input.disabled=!checked);if(checked){selected++;const unit=Number(line.dataset.price);amount+=(unit+feeFor(unit))*Number(line.querySelector('.clothing-qty').value||0);}});total.textContent='R'+amount.toFixed(2);submit.disabled=selected===0;};form.querySelectorAll('.clothing-toggle,.clothing-qty').forEach(input=>input.addEventListener('change',refresh));refresh();});</script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts/contentNavbarLayout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\frontend\team-selection\clothing.blade.php ENDPATH**/ ?>