<?php $__env->startSection('title', $case->case_number); ?>
<?php $__env->startSection('content'); ?>
<div class="container-xxl flex-grow-1 container-p-y">
  <div class="d-flex flex-wrap justify-content-between gap-2 mb-4"><div><h4 class="mb-1"><?php echo e($case->case_number); ?></h4><p class="text-muted mb-0"><?php echo e($case->event->name); ?> · <?php echo e($case->player->full_name); ?></p></div><span class="badge bg-label-warning align-self-start fs-6"><?php echo e(str($case->status)->replace('_',' ')->title()); ?></span></div>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="alert alert-danger"><ul class="mb-0"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></ul></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  <?php ($disciplinaryEnabled = \App\Models\SiteSetting::disciplinarySystemEnabled()); ?>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if (! ($disciplinaryEnabled)): ?><div class="alert alert-warning"><i class="ti ti-lock me-1"></i>The disciplinary case system is disabled. This case is read-only and remains available for audit.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

  <div class="row g-4">
    <div class="col-lg-8">
      <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Incident and charges</h5></div><div class="card-body">
        <dl class="row mb-0"><dt class="col-sm-3">Incident</dt><dd class="col-sm-9"><?php echo e($case->incident_at->format('d M Y H:i')); ?> · <?php echo e($case->incident_location ?: 'Location not supplied'); ?></dd><dt class="col-sm-3">Reported by</dt><dd class="col-sm-9"><?php echo e($case->reporter->name); ?></dd><dt class="col-sm-3">Summary</dt><dd class="col-sm-9" style="white-space:pre-wrap"><?php echo e($case->summary); ?></dd></dl>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $case->charges; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $charge): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="border rounded p-3 mt-3"><strong><?php echo e($charge->rule_code ? $charge->rule_code.' · ' : ''); ?><?php echo e($charge->rule_title); ?></strong><div class="text-muted mt-1"><?php echo e($charge->allegation); ?></div><span class="badge bg-label-secondary mt-2"><?php echo e(ucfirst($charge->finding)); ?><?php echo e($charge->finding === 'proven' ? ' · '.$charge->points.' points' : ''); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      </div></div>

      <div class="card mb-4"><div class="card-header d-flex justify-content-between"><h5 class="mb-0">Evidence</h5><span class="badge bg-secondary">Private</span></div><div class="card-body">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $case->evidence; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="border-bottom pb-3 mb-3"><strong><?php echo e($item->title); ?></strong><small class="text-muted d-block"><?php echo e($item->submitter?->name); ?> · <?php echo e($item->created_at->format('d M Y H:i')); ?></small><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->statement): ?><p class="mt-2 mb-0" style="white-space:pre-wrap"><?php echo e($item->statement); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->file_path): ?><a href="<?php echo e(route('backend.disciplinary.cases.evidence.download', [$case, $item])); ?>">Download <?php echo e($item->original_name); ?></a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-muted">No evidence added.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($disciplinaryEnabled): ?><form method="POST" enctype="multipart/form-data" action="<?php echo e(route('backend.disciplinary.cases.evidence.store', $case)); ?>" class="row g-2"><?php echo csrf_field(); ?><div class="col-md-4"><input name="title" class="form-control" placeholder="Evidence title" required></div><div class="col-md-5"><input type="file" name="evidence_file" class="form-control" required></div><div class="col-md-3"><button class="btn btn-outline-primary w-100">Upload</button></div></form><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      </div></div>

      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($disciplinaryEnabled): ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('manage', $case)): ?>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(in_array($case->status, ['submitted','triage'])): ?>
      <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Triage</h5></div><div class="card-body"><form method="POST" action="<?php echo e(route('backend.disciplinary.cases.triage', $case)); ?>"><?php echo csrf_field(); ?><textarea name="reason" class="form-control mb-3" rows="3" placeholder="Triage notes; mandatory when dismissing"></textarea><div class="d-flex gap-2"><button name="action" value="proceed" class="btn btn-primary">Issue notice and request response</button><button name="action" value="dismiss" class="btn btn-outline-danger">Dismiss with reason</button></div></form></div></div>
      <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(in_array($case->status, ['awaiting_response','panel_review'])): ?>
      <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Appoint independent panel</h5></div><div class="card-body"><form method="POST" action="<?php echo e(route('backend.disciplinary.cases.panel', $case)); ?>"><?php echo csrf_field(); ?><div class="row g-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php for($i=0;$i<3;$i++): ?><div class="col-md-8"><select name="members[<?php echo e($i); ?>][user_id]" class="form-select" required><option value="">Select panel member</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $panelCandidates; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $candidate): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($candidate->id); ?>"><?php echo e($candidate->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div><div class="col-md-4"><select name="members[<?php echo e($i); ?>][role]" class="form-select"><option value="<?php echo e($i===0 ? 'chair' : 'member'); ?>"><?php echo e($i===0 ? 'Chair' : 'Member'); ?></option></select></div><?php endfor; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><button class="btn btn-outline-primary mt-3">Appoint panel</button></form></div></div>
      <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <?php endif; ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($disciplinaryEnabled): ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('decide', $case)): ?>
      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$case->decisions->count()): ?>
      <div class="card border-primary mb-4"><div class="card-header"><h5 class="mb-0">Finalize panel decision</h5></div><div class="card-body"><form method="POST" action="<?php echo e(route('backend.disciplinary.cases.decision', $case)); ?>"><?php echo csrf_field(); ?><div class="row g-3"><div class="col-md-4"><label class="form-label">Outcome</label><select name="outcome" class="form-select"><option value="upheld">Upheld</option><option value="partially_upheld">Partially upheld</option><option value="dismissed">Not proven / dismissed</option></select></div><div class="col-md-4"><label class="form-label">Sanction</label><select name="sanctions[0][type]" class="form-select"><option value="warning">Formal warning</option><option value="points">Points</option><option value="event_disqualification">Event disqualification</option><option value="suspension">Suspension</option></select></div><div class="col-md-4"><label class="form-label">Scope</label><select name="sanctions[0][scope]" class="form-select"><option value="event">This event</option><option value="series">Series</option><option value="global">All Cape Tennis events</option></select></div><div class="col-md-6"><label class="form-label">Starts</label><input type="date" name="sanctions[0][starts_at]" value="<?php echo e(today()->format('Y-m-d')); ?>" class="form-control"></div><div class="col-md-6"><label class="form-label">Ends</label><input type="date" name="sanctions[0][ends_at]" class="form-control"></div><div class="col-12"><label class="form-label">Full reasons *</label><textarea name="reasons" class="form-control" rows="7" required minlength="20"></textarea></div><div class="col-12"><label class="form-label">Sanction details</label><textarea name="sanctions[0][details]" class="form-control" rows="3"></textarea></div></div><div class="alert alert-warning mt-3">Final decisions are immutable. Corrections must go through an appeal or formal reversal.</div><button class="btn btn-primary">Finalize and serve decision</button></form></div></div>
      <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      <?php endif; ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

      <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $case->decisions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $decision): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="card border-success mb-4"><div class="card-header"><h5 class="mb-0">Decision: <?php echo e(str($decision->outcome)->replace('_',' ')->title()); ?></h5></div><div class="card-body"><p style="white-space:pre-wrap"><?php echo e($decision->reasons); ?></p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $decision->sanctions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $sanction): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span class="badge bg-label-danger me-2"><?php echo e(str($sanction->type)->replace('_',' ')->title()); ?> · <?php echo e(ucfirst($sanction->scope)); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($sanction->ends_at): ?>to <?php echo e($sanction->ends_at->format('d M Y')); ?><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </div>

    <div class="col-lg-4">
      <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Panel</h5></div><div class="card-body"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $case->assignments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $assignment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="mb-3"><strong><?php echo e($assignment->user->name); ?></strong> <span class="badge bg-label-primary"><?php echo e(ucfirst($assignment->role)); ?></span><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($assignment->recused_at): ?><span class="badge bg-danger">Recused</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($assignment->user_id === auth()->id() && !$assignment->recused_at): ?><form method="POST" action="<?php echo e(route('backend.disciplinary.cases.panel.conflict', [$case,$assignment])); ?>" class="mt-2"><?php echo csrf_field(); ?><input type="hidden" name="conflict" value="1"><input name="notes" class="form-control form-control-sm mb-1" placeholder="Conflict reason"><button class="btn btn-sm btn-outline-danger">Declare conflict and recuse</button></form><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-muted mb-0">No panel appointed.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div>
      <div class="card"><div class="card-header"><h5 class="mb-0">Audit timeline</h5></div><div class="card-body"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $case->timeline->sortByDesc('created_at'); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $entry): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="border-start ps-3 pb-3"><strong><?php echo e(str($entry->action)->replace(['.','_'],' ')->title()); ?></strong><small class="text-muted d-block"><?php echo e($entry->created_at->format('d M Y H:i')); ?> · <?php echo e($entry->actor?->name ?? 'System'); ?></small><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($entry->notes): ?><div class="small mt-1"><?php echo e($entry->notes); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div>
    </div>
  </div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.backend', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\ct\resources\views\backend\disciplinary\cases\show.blade.php ENDPATH**/ ?>