<div class="card">
  <div class="card-header d-flex justify-content-between align-items-start"><div><h5 class="mb-1">Invitation selection</h5><p class="text-muted small mb-0">Choose the Series rankings to use. Changes save immediately.</p></div><span class="badge bg-label-primary"><?php echo e($rankingCategoryLinks->where('enabled', true)->count()); ?> selected</span></div>
  <div class="card-body">
    <div class="row g-3 mb-3"><div class="col-md-6"><span class="text-muted small d-block">Parent series</span><strong><?php echo e($event->series?->name ?? 'Not linked'); ?></strong></div><div class="col-md-3"><span class="text-muted small d-block">Ranking lists</span><strong><?php echo e($rankingLists->count()); ?></strong></div><div class="col-md-3"><span class="text-muted small d-block">Published runs</span><strong><?php echo e($publishedRuns->count()); ?></strong></div></div>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(($event->series?->minimum_events_for_team_selection ?? 1) > 1): ?>
      <div class="alert alert-info py-2">
        <strong>Team-selection eligibility:</strong>
        players need at least <?php echo e($event->series->minimum_events_for_team_selection); ?> actual event results.
        Ranked players below this minimum remain visible in the rankings but are skipped when this batch is generated.
      </div>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    <div class="d-flex justify-content-end mb-3"><form method="POST" action="<?php echo e(route('backend.masters.sync-categories', $event)); ?>"><?php echo csrf_field(); ?><button class="btn btn-outline-primary btn-sm">Sync new Series rankings</button></form></div>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$event->series): ?><div class="alert alert-danger">Blocked: link this event to a series.</div>
    <?php elseif($rankingCategoryLinks->isEmpty()): ?><div class="alert alert-warning">Sync the Series ranking lists to create the available Masters categories.</div><form method="POST" action="<?php echo e(route('backend.masters.sync-categories', $event)); ?>" class="mt-3"><?php echo csrf_field(); ?><button class="btn btn-primary">Sync categories from Series rankings</button></form>
    <?php elseif($rankingLists->isEmpty() || $publishedRuns->isEmpty()): ?><div class="alert alert-warning">A published ranking source is required before invitations can be generated.</div>
    <?php else: ?>
      <div class="mb-4" id="masters-category-manager" data-update-url="<?php echo e(route('backend.masters.category.update', [$event, '__LINK__'])); ?>">
        <div class="d-flex justify-content-between align-items-center mb-2"><h6 class="mb-0">Series ranking categories</h6><small class="text-muted">Enable or disable · adjust Top X</small></div>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $rankingCategoryLinks; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $link): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
          <div class="category-row row g-2 align-items-center" data-link-id="<?php echo e($link->id); ?>"><div class="col-7 col-md-8"><strong><?php echo e($link->rankingList?->category?->name ?? 'Ranking list #'.$link->ranking_list_id); ?></strong><div class="small text-muted"><?php echo e($link->categoryEvent?->category?->name ?? $link->category_name); ?></div></div><div class="col-5 col-md-4 d-flex justify-content-end align-items-center gap-2"><div class="stepper" aria-label="Top X"><button type="button" data-step="-1" aria-label="Decrease Top X">−</button><output data-top-x><?php echo e($link->top_x); ?></output><button type="button" data-step="1" aria-label="Increase Top X">+</button></div><button type="button" class="btn btn-sm <?php echo e($link->enabled ? 'btn-success' : 'btn-outline-secondary'); ?> category-toggle" data-enabled="<?php echo e($link->enabled ? 1 : 0); ?>"><span class="category-state"><?php echo e($link->enabled ? 'Enabled' : 'Off'); ?></span></button></div></div>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
      </div>
      <form method="POST" action="<?php echo e(route('backend.masters.generate', $event)); ?>"><?php echo csrf_field(); ?><input type="hidden" name="ranking_run_id" value="<?php echo e($publishedRuns->last()); ?>"><input type="hidden" name="top_x" value="8"><input type="hidden" name="series_id" value="<?php echo e($event->series_id); ?>"><h6 class="mt-4">Ranking-to-category mapping</h6>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $rankingCategoryLinks->where('enabled', true); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $link): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="row g-2 align-items-end mb-2"><div class="col-md-5"><label class="form-label">Ranking list</label><input class="form-control" value="<?php echo e($link->rankingList?->category?->name ?? 'Ranking list #'.$link->ranking_list_id); ?>" readonly><input type="hidden" name="mappings[<?php echo e($index); ?>][ranking_list_id]" value="<?php echo e($link->ranking_list_id); ?>"></div><div class="col-md-7"><label class="form-label">Masters category</label><input class="form-control" value="<?php echo e($link->categoryEvent?->category?->name ?? $link->category_name); ?>" readonly><input type="hidden" name="mappings[<?php echo e($index); ?>][category_event_id]" value="<?php echo e($link->category_event_id); ?>"></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <button class="btn btn-primary mt-3">Generate invitation batch</button>
      </form>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
  </div>
</div>
<?php /**PATH C:\wamp64\www\ct\resources\views\backend\event\masters\_setup.blade.php ENDPATH**/ ?>