@extends('layouts.backend')
@section('title', 'Trials communications')
@section('content')
<a class="btn btn-outline-primary mb-3" href="{{ route('backend.event-mail-log.index',$event) }}">Event email log</a>
<form method="get" class="mb-3"><label>Find an individual <input name="person_search" value="{{ request('person_search') }}" class="form-control" maxlength="100"></label><button class="btn btn-outline-primary">Search players</button><p class="text-muted">Selectors show up to 500 matches. Search by name to find another individual.</p></form>
<h4>{{ $event->name }} — Invitations and reminders</h4>
<p>Choose recipients, edit the whole message, then review exact combined emails before sending. Invitations are optional.</p>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ route('backend.interprovincial-trials.communications.preview',$event) }}" class="card card-body mb-4">
@csrf
@if($editing)<input type="hidden" name="schedule_id" value="{{ $editing->id }}"><div class="alert alert-info">Editing reminder schedule {{ $editing->id }}. Review and approve its new schedule before changes apply.</div>@endif
<label class="form-label">Saved template</label><select id="trial-template" class="form-select mb-3"><option value="">Write a message</option>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }}</option>@endforeach</select>
<div class="row g-3"><div class="col-md-6"><label class="form-label">Audience</label><select name="audience" class="form-select"><option value="all" @selected(old('audience',$editing?->options['audience'] ?? 'all')==='all')>Everyone — nominees and current teams</option><option value="nominations" @selected(old('audience',$editing?->options['audience'] ?? 'all')==='nominations')>All nominated players</option><option value="teams" @selected(old('audience',$editing?->options['audience'] ?? 'all')==='teams')>Current teams (including draft)</option></select></div>
<div class="col-md-6"><label class="form-label">Region</label><select name="region_id" class="form-select"><option value="">Whole authorised event</option>@foreach($regions as $region)<option value="{{ $region->id }}" @selected((string)old('region_id',$editing?->options['region_id'] ?? '')===(string)$region->id)>{{ $region->region_name }}</option>@endforeach</select><div class="form-text">Trials nominees belong to their programme’s event region.</div></div>
<div class="col-md-6"><label class="form-label">Current status</label><select name="filter" class="form-select">@foreach(['all'=>'Everyone','not_registered'=>'Not registered / awaiting response','payment_pending'=>'Payment outstanding','paid'=>'Paid','declined'=>'Declined','confirmed'=>'Confirmed'] as $value=>$label)<option value="{{ $value }}" @selected(($editing?->options['filter'] ?? 'all')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Categories (leave empty for all)</label><select multiple name="category_ids[]" class="form-select">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(in_array($category->id,$editing?->options['category_ids'] ?? []))>{{ $category->category?->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Teams (leave empty for all)</label><select multiple name="tiers[]" class="form-select">@foreach(['A','B','C','D','E','F'] as $tier)<option @selected(in_array($tier,$editing?->options['tiers'] ?? []))>{{ $tier }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Individual nominees (leave empty for all)</label><select multiple name="nominee_ids[]" class="form-select">@foreach($nominees as $nominee)<option value="{{ $nominee->id }}" @selected(($editing?->options['audience'] ?? '')==='nominations' && in_array($nominee->id,$editing?->options['individual_ids'] ?? []))>{{ $nominee->player?->full_name ?? trim($nominee->nominee_name.' '.$nominee->nominee_surname) }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Individual team players (leave empty for all)</label><select multiple name="slot_ids[]" class="form-select">@foreach($slots as $slot)<option value="{{ $slot->id }}" @selected(($editing?->options['audience'] ?? '')==='teams' && in_array($slot->id,$editing?->options['individual_ids'] ?? []))>{{ $slot->player?->full_name }} — {{ $slot->tier }}</option>@endforeach</select></div></div>
<label class="form-label mt-3">Recipients</label><select name="recipients" class="form-select">@foreach(['players'=>'Players and linked parents','managers'=>'Regional managers — selected roster summary','both'=>'Players/parents and regional managers'] as $value=>$label)<option value="{{ $value }}" @selected(($editing?->options['recipients'] ?? 'players')===$value)>{{ $label }}</option>@endforeach</select><p class="text-muted">Available at every event stage. Regional managers receive the selected roster for their event region.</p><label class="form-label mt-3">Subject</label><input name="subject" id="trial-subject" class="form-control" required maxlength="255" value="{{ old('subject',$editing?->subject ?? 'Invitation: {event}') }}">
<label class="form-label mt-3">Message</label><textarea name="body" id="trial-body" rows="10" class="form-control" required>{{ old('body',$editing?->body ?? "You are invited to {event}.\n\n{players}\n\nFee: R{fee}\nDeadline: {deadline}\n\nRegister or respond on the event page: {url}") }}</textarea>
<p class="text-muted mt-2">Available variables: {event}, {players}, {fee}, {deadline}, {url}. All text is editable.</p>
<label class="form-label">Template name (optional)</label><input name="name" class="form-control mb-3" maxlength="255">
<div class="d-flex flex-wrap gap-2"><button class="btn btn-primary">Preview recipients and messages</button><button type="submit" formaction="{{ route('backend.interprovincial-trials.communications.templates',$event) }}" class="btn btn-outline-primary">Save reusable template</button></div>
</form>
<h5>System messages awaiting review</h5>
<p>Registration, withdrawal and refund messages wait here for exact recipient and message approval.</p>
@forelse($pendingDrafts as $draft)<div class="card card-body mb-2"><strong>{{ $draft->subject }}</strong><div>{{ count($draft->recipients) }} recipients awaiting review</div><form method="post" action="{{ route('backend.event-communications.drafts.preview',[$event,$draft]) }}">@csrf<button class="btn btn-outline-primary mt-2">Preview exact recipients and messages</button></form></div>@empty<p>No system messages awaiting review.</p>@endforelse
@if($transactionBatches->isNotEmpty())<h5>Approved system-message reports</h5><ul>@foreach($transactionBatches as $systemBatch)<li><a href="{{ route('backend.event-communications.index',['event'=>$event,'batch'=>$systemBatch->id]) }}">#{{ $systemBatch->id }} — {{ $systemBatch->subject }} — mail-server acceptance report</a></li>@endforeach</ul>@endif
<h5>Reminder review schedules</h5>@forelse($schedules as $schedule)<div class="card card-body mb-2"><a href="{{ route('backend.interprovincial-trials.communications.index',$event) }}?edit_schedule={{ $schedule->id }}" class="mb-2">Review this reminder / edit schedule</a><div>{{ $schedule->subject }} — {{ !$schedule->active ? 'Paused / completed' : ($schedule->next_send_at->isPast() ? 'Due — review and approval required' : 'Awaiting review time') }} — next {{ $schedule->next_send_at }}</div>@if($schedule->active)<form method="post" action="{{ route('backend.interprovincial-trials.communications.pause',[$event,$schedule]) }}">@csrf<button class="btn btn-sm btn-outline-warning mt-2">Pause schedule</button></form>@endif</div>@empty<p>No scheduled reminders.</p>@endforelse
<h5>Send history</h5>
<p><a href="{{ route('backend.event-communications.index', $event) }}">Invitation send report and reviewed failed-email retries</a></p>
<form method="get" class="mb-3"><label class="form-label">Approved batch</label><select name="batch" class="form-select" onchange="this.form.submit()"><option value="">All event email history</option>@foreach($batches as $candidate)<option value="{{ $candidate->id }}" @selected($batch?->id===$candidate->id)>#{{ $candidate->id }} — {{ $candidate->subject }} — {{ count($candidate->recipients) }} approved recipients</option>@endforeach</select></form>
@if($batch)<p>{{ count($batch->recipients) }} approved recipients; {{ count($batch->excluded) }} contacts requiring follow-up.</p>@endif
<p>{{ $delivery['total'] }} recorded · {{ $delivery['queued'] }} queued · {{ $delivery['sending'] }} sending · {{ $delivery['server_accepted'] }} mail server accepted · {{ $delivery['failed'] }} failed · {{ $delivery['skipped'] }} skipped · {{ $delivery['unverified'] }} acceptance unverified · {{ $delivery['sandbox_accepted'] }} sandbox accepted.</p>
@if($batch && $delivery['all_server_accepted'] && count($batch->recipients)===$delivery['total'])<div class="alert alert-success">Every approved email in this batch was accepted by the mail server.</div>@endif
<p class="text-muted">Mail server acceptance does not confirm inbox delivery or reading. Missing contacts above were not queued.</p><div class="table-responsive"><table class="table"><thead><tr><th>Recipient</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>@foreach($logs as $log)<tr><td>{{ $log->recipient_email }}</td><td>@include('backend.partials.email-delivery-status', ['log'=>$log])</td><td>{{ $log->sent_at ?? $log->queued_at }}</td><td>@if($log->status==='failed')<form method="post" action="{{ route('backend.interprovincial-trials.communications.retry',[$event,$log]) }}">@csrf<details><summary>Review failed email before retry</summary><strong>To: {{ $log->recipient_email }}</strong><h6>{{ data_get($log->payload,'subject') }}</h6><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{ html_entity_decode(strip_tags(data_get($log->payload,'body','')), ENT_QUOTES | ENT_HTML5, 'UTF-8') }}</pre><label class="d-block mt-2"><input type="checkbox" name="approved_retry" value="1" required> I reviewed this recipient and exact message and approve retrying it.</label><button class="btn btn-sm btn-outline-primary mt-2">Approve retry of this exact email</button></details></form>@endif</td></tr>@endforeach</tbody></table></div>{{ $logs->links() }}
<script>
const templates = @json($templates->keyBy('id'));
document.getElementById('trial-template').addEventListener('change',function(){const selected=templates[this.value];if(selected){document.getElementById('trial-subject').value=selected.subject;document.getElementById('trial-body').value=selected.body;}});
</script>
@endsection
