@extends('layouts.backend')
@section('title', 'Review Trials messages')
@section('content')
<h4>Review exact recipients and messages — {{ $event->name }}</h4>
<p>{{ count($preview->recipients) }} combined emails. Preview expires {{ $preview->expires_at }}. Changed contacts or statuses require a new preview.</p>
@foreach($preview->recipients as $recipient)<div class="card card-body mb-3"><strong>To: {{ $recipient['email'] }}</strong><div>Players: {{ $recipient['name'] }}</div><h5 class="mt-3">{{ $recipient['subject'] }}</h5><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{ $recipient['body'] }}</pre></div>@endforeach
@if(count($preview->excluded))<div class="alert alert-warning"><strong>Contacts requiring follow-up</strong><ul>@foreach($preview->excluded as $excluded)<li>{{ $excluded['player'] }} — {{ $excluded['reason'] }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ route('backend.interprovincial-trials.communications.send',$event) }}">@csrf<input type="hidden" name="token" value="{{ $preview->token }}"><button class="btn btn-primary" @disabled(!count($preview->recipients))>Confirm and queue {{ count($preview->recipients) }} emails now</button><a class="btn btn-outline-secondary" href="{{ route('backend.interprovincial-trials.communications.index',$event) }}">Return to editing</a></form>
<hr><h5>Or approve an automatic reminder schedule</h5><p>Each run rechecks recipients against your selected status filters.</p><form method="post" action="{{ route('backend.interprovincial-trials.communications.schedules',$event) }}" class="card card-body">@csrf<input type="hidden" name="token" value="{{ $preview->token }}"><label class="form-label">First send</label><input type="datetime-local" name="start" class="form-control mb-2" required><label class="form-label">Repeat every number of hours (blank for one send)</label><input type="number" name="repeat_hours" min="1" max="8760" class="form-control mb-2"><label class="form-label">Stop sending after (optional)</label><input type="datetime-local" name="stop" class="form-control mb-3"><button class="btn btn-outline-primary">Approve this message and schedule</button></form>
@endsection
