@extends('layouts.backend')
@section('title', 'Trials communications')
@section('content')
<h4>{{ $event->name }} — Invitations and reminders</h4>
<p>Choose recipients, edit the whole message, then review exact combined emails before sending. Invitations are optional.</p>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ route('backend.interprovincial-trials.communications.preview',$event) }}" class="card card-body mb-4">
@csrf
@if($editing)<input type="hidden" name="schedule_id" value="{{ $editing->id }}"><div class="alert alert-info">Editing reminder schedule {{ $editing->id }}. Review and approve its new schedule before changes apply.</div>@endif
<label class="form-label">Saved template</label><select id="trial-template" class="form-select mb-3"><option value="">Write a message</option>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }}</option>@endforeach</select>
<div class="row g-3"><div class="col-md-6"><label class="form-label">Audience</label><select name="audience" class="form-select"><option value="nominations" @selected(($editing?->options['audience'] ?? 'nominations')==='nominations')>Published Trials nominees</option><option value="teams" @selected(($editing?->options['audience'] ?? 'nominations')==='teams')>Finalised teams</option></select></div>
<div class="col-md-6"><label class="form-label">Current status</label><select name="filter" class="form-select">@foreach(['all'=>'Everyone','not_registered'=>'Not registered / awaiting response','payment_pending'=>'Payment outstanding','paid'=>'Paid','declined'=>'Declined','confirmed'=>'Confirmed'] as $value=>$label)<option value="{{ $value }}" @selected(($editing?->options['filter'] ?? 'all')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Categories (leave empty for all)</label><select multiple name="category_ids[]" class="form-select">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(in_array($category->id,$editing?->options['category_ids'] ?? []))>{{ $category->category?->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Teams (leave empty for all)</label><select multiple name="tiers[]" class="form-select">@foreach(['A','B','C','D','E','F'] as $tier)<option @selected(in_array($tier,$editing?->options['tiers'] ?? []))>{{ $tier }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Individual nominees (leave empty for all)</label><select multiple name="nominee_ids[]" class="form-select">@foreach($nominees as $nominee)<option value="{{ $nominee->id }}" @selected(($editing?->options['audience'] ?? '')==='nominations' && in_array($nominee->id,$editing?->options['individual_ids'] ?? []))>{{ $nominee->player?->full_name ?? trim($nominee->nominee_name.' '.$nominee->nominee_surname) }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Individual team players (leave empty for all)</label><select multiple name="slot_ids[]" class="form-select">@foreach($slots as $slot)<option value="{{ $slot->id }}" @selected(($editing?->options['audience'] ?? '')==='teams' && in_array($slot->id,$editing?->options['individual_ids'] ?? []))>{{ $slot->player?->full_name }} — {{ $slot->tier }}</option>@endforeach</select></div></div>
<label class="form-label mt-3">Subject</label><input name="subject" id="trial-subject" class="form-control" required maxlength="255" value="{{ old('subject',$editing?->subject ?? 'Invitation: {event}') }}">
<label class="form-label mt-3">Message</label><textarea name="body" id="trial-body" rows="10" class="form-control" required>{{ old('body',$editing?->body ?? "You are invited to {event}.\n\n{players}\n\nFee: R{fee}\nDeadline: {deadline}\n\nRegister or respond on the event page: {url}") }}</textarea>
<p class="text-muted mt-2">Available variables: {event}, {players}, {fee}, {deadline}, {url}. All text is editable.</p>
<label class="form-label">Template name (optional)</label><input name="name" class="form-control mb-3" maxlength="255">
<div class="d-flex flex-wrap gap-2"><button class="btn btn-primary">Preview recipients and messages</button><button type="submit" formaction="{{ route('backend.interprovincial-trials.communications.templates',$event) }}" class="btn btn-outline-primary">Save reusable template</button></div>
</form>
<h5>Approved reminder schedules</h5>@forelse($schedules as $schedule)<div class="card card-body mb-2"><a href="{{ route('backend.interprovincial-trials.communications.index',$event) }}?edit_schedule={{ $schedule->id }}" class="mb-2">Edit and approve schedule</a><div>{{ $schedule->subject }} — {{ $schedule->active ? 'Active' : 'Paused / completed' }} — next {{ $schedule->next_send_at }}</div>@if($schedule->active)<form method="post" action="{{ route('backend.interprovincial-trials.communications.pause',[$event,$schedule]) }}">@csrf<button class="btn btn-sm btn-outline-warning mt-2">Pause schedule</button></form>@endif</div>@empty<p>No scheduled reminders.</p>@endforelse
<h5>Send history</h5><div class="table-responsive"><table class="table"><thead><tr><th>Recipient</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>@foreach($logs as $log)<tr><td>{{ $log->recipient_email }}</td><td>{{ $log->status }}</td><td>{{ $log->sent_at ?? $log->queued_at }}</td><td>@if($log->status==='failed')<form method="post" action="{{ route('backend.interprovincial-trials.communications.retry',[$event,$log]) }}">@csrf<button class="btn btn-sm btn-outline-primary">Retry failed email</button></form>@endif</td></tr>@endforeach</tbody></table></div>{{ $logs->links() }}
<script>
const templates = @json($templates->keyBy('id'));
document.getElementById('trial-template').addEventListener('change',function(){const selected=templates[this.value];if(selected){document.getElementById('trial-subject').value=selected.subject;document.getElementById('trial-body').value=selected.body;}});
</script>
@endsection
